# Generated by Django 5.2.16 on 2026-07-30 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_document_manager_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmembership',
            name='role',
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'revoked')), _connector='OR'), name='organization_membership_revocation_complete'),
        ),
    ]
