# Generated by Django 5.2.16 on 2026-07-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logical_id', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField()),
                ('manifest', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('protocol', models.CharField(max_length=16)),
                ('risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('side_effecting', models.BooleanField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_definitions', to='tenancy.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ToolBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logical_id', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField()),
                ('manifest', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('approval_required', models.BooleanField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_bindings', to='tenancy.organization')),
                ('tool_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='tools.tooldefinition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tooldefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'logical_id', 'version'), name='uniq_tool_definition_org_logical_version'),
        ),
        migrations.AddConstraint(
            model_name='toolbinding',
            constraint=models.UniqueConstraint(fields=('organization', 'logical_id', 'version'), name='uniq_tool_binding_org_logical_version'),
        ),
    ]
