# Generated by Django 5.2.16 on 2026-07-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('identity', '0002_consumertoken'),
        ('releases', '0002_releasecanary'),
        ('tenancy', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('binding_role', models.CharField(max_length=128)),
                ('tool_ref', models.CharField(max_length=160)),
                ('binding_checksum', models.CharField(max_length=64)),
                ('request_checksum', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('risk', models.CharField(max_length=16)),
                ('side_effecting', models.BooleanField()),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('outcome_unknown', 'Outcome unknown'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending_approval', max_length=20)),
                ('outcome_reason', models.CharField(blank=True, max_length=64)),
                ('redacted_input', models.JSONField(blank=True, default=dict)),
                ('redacted_output', models.JSONField(blank=True, default=dict)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_invocations', to='identity.consumer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to='tenancy.organization')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_invocations', to='releases.scenariorelease')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_invocations', to='catalog.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_checksum', models.CharField(max_length=64)),
                ('approver_roles', models.JSONField(default=list)),
                ('requested_by', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('decided_by', models.CharField(blank=True, max_length=200)),
                ('decision_reason', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_approval_requests', to='tenancy.organization')),
                ('invocation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval', to='tools.toolinvocation')),
            ],
        ),
        migrations.AddIndex(
            model_name='toolinvocation',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='tools_tooli_organiz_4c111d_idx'),
        ),
        migrations.AddConstraint(
            model_name='toolinvocation',
            constraint=models.UniqueConstraint(fields=('consumer', 'idempotency_key'), name='uniq_tool_invocation_consumer_idempotency'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['organization', 'status', 'expires_at'], name='tools_appro_organiz_021317_idx'),
        ),
    ]
