# Generated by Django 5.2.16 on 2026-07-31 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_approvalrequest_decided_by_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='approver_roles',
        ),
    ]
