# Generated by Django 5.2.16 on 2026-07-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(help_text='Stable authenticated subject (OIDC sub, service account, mTLS CN).', max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('protocol', models.CharField(choices=[('rest', 'REST'), ('mcp', 'MCP')], max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumers', to='tenancy.organization')),
            ],
            options={
                'ordering': ['organization_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConsumerBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capabilities', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='identity.consumer')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_bindings', to='catalog.scenario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='consumer',
            constraint=models.UniqueConstraint(fields=('organization', 'subject'), name='uniq_consumer_org_subject'),
        ),
        migrations.AddConstraint(
            model_name='consumerbinding',
            constraint=models.UniqueConstraint(fields=('consumer', 'scenario'), name='uniq_binding_consumer_scenario'),
        ),
    ]
