# Generated by Django 5.2.16 on 2026-07-27 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_aiproject_owner_membership'),
        ('documents', '0006_scenario_document_set_access'),
        ('identity', '0008_delegated_assignments'),
        ('tenancy', '0003_document_manager_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsetmanagerassignment',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsetmanagerassignment',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_document_set_manager_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentsetmanagerassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='projectadministratorassignment',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectadministratorassignment',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_project_administrator_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectadministratorassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='scenarioeditorassignment',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenarioeditorassignment',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_scenario_editor_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenarioeditorassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='documentsetmanagerassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'revoked')), _connector='OR'), name='document_set_manager_assignment_revocation_complete'),
        ),
        migrations.AddConstraint(
            model_name='projectadministratorassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'revoked')), _connector='OR'), name='project_administrator_assignment_revocation_complete'),
        ),
        migrations.AddConstraint(
            model_name='scenarioeditorassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'revoked')), _connector='OR'), name='scenario_editor_assignment_revocation_complete'),
        ),
    ]
