# Generated by Django 5.2.16 on 2026-07-30 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_scenario_type'),
        ('documents', '0008_document_set_quarantine'),
        ('identity', '0009_delegated_assignment_revocation'),
        ('tenancy', '0004_remove_organizationmembership_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSetResponsibilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('responsibility', models.CharField(choices=[('document_set_metadata_viewer', 'Document-set metadata viewer'), ('document_set_content_reader', 'Document-set content reader'), ('document_set_manager', 'Document-set manager')], max_length=48)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibility_assignments', to='documents.documentset')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization_id', 'document_set_id', 'membership_id', 'responsibility'],
                'constraints': [models.UniqueConstraint(fields=('document_set', 'membership', 'responsibility'), name='uniq_document_set_responsibility_assignment'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'revoked')), _connector='OR'), name='document_set_responsibility_assignment_revocation_complete')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationResponsibilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('responsibility', models.CharField(choices=[('organization_administrator', 'Organization administrator'), ('organization_auditor', 'Organization auditor')], max_length=48)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization_id', 'membership_id', 'responsibility'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'membership', 'responsibility'), name='uniq_organization_responsibility_assignment'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'revoked')), _connector='OR'), name='organization_responsibility_assignment_revocation_complete'), models.CheckConstraint(condition=models.Q(('expires_at__isnull', False), ('responsibility', 'organization_administrator'), _negated=True), name='organization_administrator_non_expiring')],
            },
        ),
        migrations.CreateModel(
            name='PlatformResponsibilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsibility', models.CharField(choices=[('global_administrator', 'Global administrator')], default='global_administrator', max_length=48)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_platform_responsibility_assignments', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_platform_responsibility_assignments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_responsibility_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('responsibility',), name='uniq_active_platform_responsibility'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'revoked')), _connector='OR'), name='platform_responsibility_assignment_revocation_complete')],
            },
        ),
        migrations.CreateModel(
            name='ProjectResponsibilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('responsibility', models.CharField(choices=[('project_viewer', 'Project viewer'), ('project_administrator', 'Project administrator')], max_length=48)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibility_assignments', to='catalog.aiproject')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'membership_id', 'responsibility'],
                'constraints': [models.UniqueConstraint(fields=('project', 'membership', 'responsibility'), name='uniq_project_responsibility_assignment'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'revoked')), _connector='OR'), name='project_responsibility_assignment_revocation_complete')],
            },
        ),
        migrations.CreateModel(
            name='ScenarioResponsibilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('responsibility', models.CharField(choices=[('scenario_viewer', 'Scenario viewer'), ('scenario_editor', 'Scenario editor'), ('scenario_release_manager', 'Scenario release manager'), ('scenario_runtime_operator', 'Scenario runtime operator'), ('scenario_approver', 'Scenario approver')], max_length=48)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organizationmembership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibility_assignments', to='catalog.scenario')),
            ],
            options={
                'ordering': ['organization_id', 'scenario_id', 'membership_id', 'responsibility'],
                'constraints': [models.UniqueConstraint(fields=('scenario', 'membership', 'responsibility'), name='uniq_scenario_responsibility_assignment'), models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', True), ('revoked_by__isnull', True), ('status', 'active')), models.Q(('revoked_at__isnull', False), ('revoked_by__isnull', False), ('status', 'revoked')), _connector='OR'), name='scenario_responsibility_assignment_revocation_complete')],
            },
        ),
    ]
