# Generated by Django 5.2.16 on 2026-07-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_documentsetresponsibilityassignment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentSetManagerAssignment',
        ),
        migrations.DeleteModel(
            name='GlobalAdministrator',
        ),
        migrations.DeleteModel(
            name='ProjectAdministratorAssignment',
        ),
        migrations.DeleteModel(
            name='ScenarioEditorAssignment',
        ),
    ]
