# Generated by Django 5.2.17 on 2026-09-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0012_responsibility_assignment_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenarioresponsibilityassignment",
            name="responsibility",
            field=models.CharField(
                choices=[
                    ("scenario_viewer", "Scenario viewer"),
                    ("scenario_editor", "Scenario editor"),
                    ("scenario_manager", "Senaryo yöneticisi"),
                    ("scenario_release_manager", "Scenario release manager"),
                    ("scenario_runtime_operator", "Scenario runtime operator"),
                    ("scenario_approver", "Scenario approver"),
                ],
                max_length=48,
            ),
        ),
    ]
