# Generated by Django 5.2.17 on 2026-09-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0013_add_scenario_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectresponsibilityassignment",
            name="responsibility",
            field=models.CharField(
                choices=[
                    ("project_viewer", "Project viewer"),
                    ("project_editor", "Proje düzenleyeni"),
                    ("project_manager", "Proje yöneticisi"),
                    ("project_administrator", "Project administrator"),
                ],
                max_length=48,
            ),
        ),
    ]
