# Generated by Django 5.2.16 on 2026-07-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0002_rename_document_indexeddocument'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logical_id', models.CharField(max_length=128)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('lifecycle_state', models.CharField(choices=[('active', 'Active'), ('tombstoned', 'Tombstoned')], default='active', max_length=16)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_documents', to='tenancy.organization')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_documents', to='ingestion.source')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logical_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sets', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('promotable', 'Promotable'), ('active', 'Active'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('built_index_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_set_versions', to='ingestion.indexversion')),
                ('document_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.documentset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_set_versions', to='tenancy.organization')),
            ],
            options={
                'ordering': ['document_set_id', 'version'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('mime_type', models.CharField(max_length=128)),
                ('object_key', models.CharField(max_length=512)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('parser', models.CharField(blank=True, max_length=32)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('element_count', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_versions', to='tenancy.organization')),
            ],
            options={
                'ordering': ['document_id', 'version'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_set_memberships', to='tenancy.organization')),
                ('document_set_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='documents.documentsetversion')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='documents.documentversion')),
            ],
            options={
                'ordering': ['document_set_version_id', 'ordinal'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'lifecycle_state'], name='documents_d_organiz_ced8ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('organization', 'logical_id'), name='uniq_document_org_logical'),
        ),
        migrations.AddConstraint(
            model_name='documentset',
            constraint=models.UniqueConstraint(fields=('organization', 'logical_id'), name='uniq_document_set_org_logical'),
        ),
        migrations.AddConstraint(
            model_name='documentsetversion',
            constraint=models.UniqueConstraint(fields=('document_set', 'version'), name='uniq_document_set_version'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uniq_document_version'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('object_key',), name='uniq_document_object_key'),
        ),
        migrations.AddConstraint(
            model_name='documentsetmembership',
            constraint=models.UniqueConstraint(fields=('document_set_version', 'document_version'), name='uniq_membership_setversion_docversion'),
        ),
    ]
