# Generated by Django 5.2.16 on 2026-07-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('documents', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSetGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_type', models.CharField(choices=[('consumer', 'Consumer'), ('service', 'Service'), ('user', 'User'), ('group', 'Group')], max_length=16)),
                ('principal_ref', models.CharField(max_length=255)),
                ('permission', models.CharField(choices=[('retrieve', 'Retrieve')], default='retrieve', max_length=16)),
                ('document_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='documents.documentset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_set_grants', to='tenancy.organization')),
            ],
            options={
                'ordering': ['document_set_id', 'principal_type', 'principal_ref'],
                'constraints': [models.UniqueConstraint(fields=('document_set', 'principal_type', 'principal_ref', 'permission'), name='uniq_document_set_grant')],
            },
        ),
        migrations.CreateModel(
            name='ScenarioDocumentSetBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('document_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_bindings', to='documents.documentset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_document_set_bindings', to='tenancy.organization')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_set_bindings', to='catalog.scenario')),
            ],
            options={
                'ordering': ['organization_id', 'scenario_id', 'document_set_id'],
                'constraints': [models.UniqueConstraint(fields=('scenario', 'document_set'), name='uniq_scenario_document_set_binding')],
            },
        ),
    ]
