# Generated by Django 5.2.17 on 2026-09-09 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_explicit_shared_data_access"),
        ("documents", "0010_active_document_set_version_constraint"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariodocumentsetgrant",
            name="shared_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenariodocumentsetgrant",
            name="shared_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_shared_scenario_data",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scenariodocumentsetgrant",
            name="shared_consumers",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddConstraint(
            model_name="scenariodocumentsetgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("shared_approved_at__isnull", True),
                        ("shared_approved_by__isnull", True),
                        ("shared_consumers", False),
                    ),
                    models.Q(
                        ("revoked_at__isnull", True),
                        ("shared_approved_at__isnull", False),
                        ("shared_approved_by__isnull", False),
                        ("shared_consumers", True),
                        ("status", "granted"),
                    ),
                    _connector="OR",
                ),
                name="scenario_shared_grant_explicit",
            ),
        ),
    ]
