# Generated by Django 5.2.16 on 2026-07-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('logical_id', models.CharField(max_length=128)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
                ('last_published_version', models.PositiveIntegerField(default=0)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_drafts', to='tenancy.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_drafts', to='catalog.aiproject')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['organization', '-updated_at'], name='builder_wor_organiz_6f6d74_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'logical_id'), name='uniq_workflow_draft_org_logical')],
            },
        ),
    ]
