# Generated by Django 5.2.16 on 2026-07-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0001_initial"),
        ("catalog", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("input_contract", "Input contract"),
                            ("output_contract", "Output contract"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("logical_id", models.CharField(max_length=128)),
                ("body", models.JSONField(default=dict)),
                ("created_by", models.CharField(max_length=200)),
                ("updated_by", models.CharField(max_length=200)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_drafts",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifact_drafts",
                        to="catalog.aiproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "artifact_type", "-updated_at"],
                        name="builder_art_org_type_upd_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "artifact_type", "logical_id"),
                        name="uniq_artifact_draft_org_type_logical",
                    )
                ],
            },
        ),
    ]
