# Generated by Django 5.2.16 on 2026-07-31 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_workflowdraft_logical_description'),
        ('catalog', '0008_remove_aiproject_owner_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactdraft',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_drafts', to='catalog.scenario'),
        ),
    ]
