# Generated by Django 5.2 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("builder", "0005_artifactdraft_scenario")]

    operations = [
        migrations.AlterField(
            model_name="artifactdraft",
            name="artifact_type",
            field=models.CharField(
                choices=[
                    ("input_contract", "Input contract"),
                    ("output_contract", "Output contract"),
                    ("prompt_template", "Prompt template"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="artifactdraft",
            name="logical_description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="artifactdraft",
            name="last_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artifactdraft",
            name="last_published_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
