# Generated by Django 5.2 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("builder", "0006_artifactdraft_prompt_publication")]

    operations = [
        migrations.AlterField(
            model_name="artifactdraft",
            name="artifact_type",
            field=models.CharField(
                choices=[
                    ("input_contract", "Input contract"),
                    ("output_contract", "Output contract"),
                    ("prompt_template", "Prompt template"),
                    ("chunking_profile", "Chunking profile"),
                    ("retrieval_profile", "Retrieval profile"),
                ],
                max_length=32,
            ),
        ),
    ]
