# Generated by Django 5.2.16 on 2026-07-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('organization_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('scenario_id', models.BigIntegerField(blank=True, null=True)),
                ('release_id', models.BigIntegerField(blank=True, null=True)),
                ('consumer_id', models.BigIntegerField(blank=True, null=True)),
                ('operation', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
