# Generated by Django 5.2.16 on 2026-07-10 15:25

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django
import pgvector.django.vector
from django.db import migrations, models


def create_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'CREATE INDEX chunk_embedding_hnsw ON ingestion_chunk '
            'USING hnsw (embedding vector_cosine_ops) '
            'WITH (m = 16, ef_construction = 64)'
        )


def drop_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP INDEX IF EXISTS chunk_embedding_hnsw')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='IndexVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('building', 'Building'), ('promotable', 'Promotable'), ('active', 'Active'), ('failed', 'Failed')], default='building', max_length=16)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_versions', to='tenancy.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_uri', models.TextField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenancy.organization')),
                ('index_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ingestion.indexversion')),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tenancy.organization')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ingestion.document')),
                ('index_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ingestion.indexversion')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('connector_type', models.CharField(choices=[('https', 'Allowlisted HTTPS'), ('s3', 'S3/MinIO object')], max_length=16)),
                ('connector_config', models.JSONField(default=dict)),
                ('parser', models.CharField(default='text', max_length=32)),
                ('chunker', models.CharField(default='fixed', max_length=32)),
                ('embedder', models.CharField(default='deterministic', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='tenancy.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('retry', 'Retry'), ('succeeded', 'Succeeded'), ('dead_letter', 'Dead letter')], default='queued', max_length=16)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('index_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run', to='ingestion.indexversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='tenancy.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ingestion.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='indexversion',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_versions', to='ingestion.source'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('index_version', 'source_uri'), name='uniq_document_index_uri'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('document', 'ordinal'), name='uniq_chunk_document_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uniq_source_org_slug'),
        ),
        migrations.AddConstraint(
            model_name='indexversion',
            constraint=models.UniqueConstraint(fields=('source', 'version'), name='uniq_index_source_version'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_hnsw_index, drop_hnsw_index)],
            state_operations=[
                migrations.AddIndex(
                    model_name='chunk',
                    index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
                ),
            ],
        ),
    ]
