# Generated by Django 5.2.16 on 2026-07-12 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_rename_document_indexeddocument'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('logical_id', models.CharField(max_length=128)),
                ('revision', models.PositiveIntegerField()),
                ('provider', models.CharField(default='openai_compatible', max_length=64)),
                ('scheme', models.CharField(default='https', max_length=8)),
                ('host', models.CharField(max_length=253)),
                ('port', models.PositiveIntegerField(default=443)),
                ('path', models.CharField(default='/v1/embeddings', max_length=512)),
                ('model', models.CharField(max_length=200)),
                ('secret_ref', models.CharField(max_length=160)),
                ('dimensions', models.PositiveIntegerField()),
                ('index_type', models.CharField(choices=[('vector', 'vector (D<=2000)'), ('halfvec', 'halfvec (D<=4000)')], default='vector', max_length=16)),
                ('normalize', models.BooleanField(default=True)),
                ('distance_metric', models.CharField(default='cosine', max_length=16)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_response_bytes', models.PositiveIntegerField(default=5000000)),
                ('max_batch_size', models.PositiveIntegerField(default=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('logical_id', 'revision'), name='uniq_embedding_profile_logical_revision')],
            },
        ),
        migrations.CreateModel(
            name='TenantEmbeddingProfileGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_grants', to='ingestion.embeddingprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_profile_grants', to='tenancy.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'embedding_profile'), name='uniq_tenant_embedding_grant')],
            },
        ),
    ]
