# Generated by Django 5.2.16 on 2026-07-12 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('ingestion', '0003_embeddingprofile_tenantembeddingprofilegrant'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexversion',
            name='dimensions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexversion',
            name='document_set_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index_versions', to='documents.documentsetversion'),
        ),
        migrations.AddField(
            model_name='indexversion',
            name='embedding_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index_versions', to='ingestion.embeddingprofile'),
        ),
        migrations.AddField(
            model_name='indexversion',
            name='index_type',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='indexversion',
            name='store_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indexversion',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_versions', to='ingestion.source'),
        ),
        migrations.AddConstraint(
            model_name='indexversion',
            constraint=models.UniqueConstraint(condition=models.Q(('document_set_version__isnull', False)), fields=('document_set_version', 'embedding_profile', 'version'), name='uniq_index_docsetver_profile_version'),
        ),
    ]
