# Generated by Django 5.2.16 on 2026-07-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_indexversion_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexversion',
            name='status',
            field=models.CharField(choices=[('building', 'Building'), ('promotable', 'Promotable'), ('active', 'Active'), ('superseded', 'Superseded'), ('failed', 'Failed')], default='building', max_length=16),
        ),
    ]
