# Generated by Django 5.2.16 on 2026-07-13 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentsetgrant_scenariodocumentsetbinding'),
        ('ingestion', '0005_alter_indexversion_status'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('logical_id', models.CharField(max_length=128)),
                ('revision', models.PositiveIntegerField()),
                ('provider', models.CharField(default='async_markdown_ocr', max_length=64)),
                ('scheme', models.CharField(default='https', max_length=8)),
                ('host', models.CharField(max_length=253)),
                ('port', models.PositiveIntegerField(default=443)),
                ('base_path', models.CharField(default='/api/v1', max_length=512)),
                ('secret_ref', models.CharField(max_length=160)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('poll_interval_seconds', models.PositiveSmallIntegerField(default=2)),
                ('max_poll_attempts', models.PositiveIntegerField(default=150)),
                ('max_upload_bytes', models.PositiveBigIntegerField(default=52428800)),
                ('max_pages', models.PositiveIntegerField(default=500)),
                ('max_result_bytes', models.PositiveIntegerField(default=10000000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('logical_id', 'revision'), name='uniq_ocr_profile_logical_revision')],
            },
        ),
        migrations.CreateModel(
            name='DocumentOcrJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('submitting', 'Submitting'), ('submitted', 'Submitted'), ('outcome_unknown', 'Outcome unknown'), ('result_persisted', 'Result persisted'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='submitting', max_length=24)),
                ('result_object_key', models.CharField(blank=True, max_length=512)),
                ('result_checksum', models.CharField(blank=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_jobs', to='documents.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_ocr_jobs', to='tenancy.organization')),
                ('ocr_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='ingestion.ocrprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document_version', 'ocr_profile'), name='uniq_document_ocr_profile_job')],
            },
        ),
        migrations.CreateModel(
            name='TenantOcrProfileGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_grants', to='ingestion.ocrprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_profile_grants', to='tenancy.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'ocr_profile'), name='uniq_tenant_ocr_grant')],
            },
        ),
    ]
