# Generated by Django 5.2.16 on 2026-07-13 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


_TENANT_TABLES = (
    "ingestion_tenantconfluenceprofilegrant",
    "ingestion_confluencesyncrun",
    "ingestion_confluencedocumentcursor",
)


def enable_confluence_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in _TENANT_TABLES:
            quoted = schema_editor.quote_name(table)
            cursor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
            cursor.execute(
                f"""
                CREATE POLICY tenant_isolation ON {quoted}
                USING (
                    organization_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint
                )
                WITH CHECK (
                    organization_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint
                )
                """
            )


def disable_confluence_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in _TENANT_TABLES:
            quoted = schema_editor.quote_name(table)
            cursor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
            cursor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentsetgrant_scenariodocumentsetbinding'),
        ('ingestion', '0006_ocrprofile_documentocrjob_tenantocrprofilegrant'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluenceSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('retry', 'Retry'), ('succeeded', 'Succeeded'), ('dead_letter', 'Dead letter')], default='queued', max_length=16)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('snapshot_complete', models.BooleanField(default=False)),
                ('discovered_count', models.PositiveIntegerField(default=0)),
                ('changed_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('fetched_bytes', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantConfluenceProfileGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='document_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='connector_sources', to='documents.documentset'),
        ),
        migrations.AlterField(
            model_name='source',
            name='connector_type',
            field=models.CharField(choices=[('https', 'Allowlisted HTTPS'), ('s3', 'S3/MinIO object'), ('confluence_dc', 'Confluence Data Center')], max_length=16),
        ),
        migrations.CreateModel(
            name='ConfluenceDocumentCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_page_id', models.CharField(max_length=64)),
                ('root_page_id', models.CharField(max_length=64)),
                ('external_version', models.PositiveBigIntegerField()),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('missing', 'Missing')], default='active', max_length=16)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confluence_cursors', to='documents.document')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confluence_cursors', to='documents.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confluence_document_cursors', to='tenancy.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confluence_document_cursors', to='ingestion.source')),
            ],
        ),
        migrations.CreateModel(
            name='ConfluenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('logical_id', models.CharField(max_length=128)),
                ('revision', models.PositiveIntegerField()),
                ('provider', models.CharField(default='confluence_dc', max_length=32)),
                ('scheme', models.CharField(default='https', max_length=8)),
                ('host', models.CharField(max_length=253)),
                ('port', models.PositiveIntegerField(default=443)),
                ('context_path', models.CharField(blank=True, max_length=512)),
                ('secret_ref', models.CharField(max_length=160)),
                ('network_policy_id', models.CharField(max_length=128)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('page_size', models.PositiveSmallIntegerField(default=50)),
                ('max_pages', models.PositiveIntegerField(default=5000)),
                ('max_depth', models.PositiveSmallIntegerField(default=50)),
                ('max_requests', models.PositiveIntegerField(default=20000)),
                ('max_retries', models.PositiveSmallIntegerField(default=2)),
                ('max_response_bytes', models.PositiveIntegerField(default=5000000)),
                ('max_page_body_bytes', models.PositiveIntegerField(default=4000000)),
                ('max_total_bytes', models.PositiveBigIntegerField(default=100000000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('logical_id', 'revision'), name='uniq_confluence_profile_logical_revision')],
            },
        ),
        migrations.AddField(
            model_name='source',
            name='confluence_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='ingestion.confluenceprofile'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confluence_profile__isnull', False), ('connector_type', 'confluence_dc'), ('document_set__isnull', False)), models.Q(models.Q(('connector_type', 'confluence_dc'), _negated=True), ('confluence_profile__isnull', True), ('document_set__isnull', True)), _connector='OR'), name='source_confluence_binding_consistent'),
        ),
        migrations.AddField(
            model_name='confluencesyncrun',
            name='candidate_set_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confluence_sync_runs', to='documents.documentsetversion'),
        ),
        migrations.AddField(
            model_name='confluencesyncrun',
            name='confluence_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_runs', to='ingestion.confluenceprofile'),
        ),
        migrations.AddField(
            model_name='confluencesyncrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confluence_sync_runs', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='confluencesyncrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confluence_sync_runs', to='ingestion.source'),
        ),
        migrations.AddField(
            model_name='confluencedocumentcursor',
            name='last_seen_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_cursors', to='ingestion.confluencesyncrun'),
        ),
        migrations.AddField(
            model_name='tenantconfluenceprofilegrant',
            name='confluence_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_document_set_grants', to='ingestion.confluenceprofile'),
        ),
        migrations.AddField(
            model_name='tenantconfluenceprofilegrant',
            name='document_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confluence_profile_grants', to='documents.documentset'),
        ),
        migrations.AddField(
            model_name='tenantconfluenceprofilegrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confluence_profile_grants', to='tenancy.organization'),
        ),
        migrations.AddConstraint(
            model_name='confluencedocumentcursor',
            constraint=models.UniqueConstraint(fields=('source', 'external_page_id'), name='uniq_confluence_source_external_page'),
        ),
        migrations.AddConstraint(
            model_name='tenantconfluenceprofilegrant',
            constraint=models.UniqueConstraint(fields=('organization', 'document_set', 'confluence_profile'), name='uniq_tenant_docset_confluence_grant'),
        ),
        migrations.RunPython(enable_confluence_rls, disable_confluence_rls),
    ]
