# Generated by Django 5.2.16 on 2026-07-13 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models

_TENANT_TABLES = (
    "ingestion_restpullcontract",
    "ingestion_tenantrestpullprofilegrant",
    "ingestion_restsyncrun",
    "ingestion_restdocumentcursor",
    "ingestion_connectorsyncschedule",
    "ingestion_connectorschedulepromotiontarget",
)


def enable_generic_rest_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in _TENANT_TABLES:
            quoted = schema_editor.quote_name(table)
            cursor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
            cursor.execute(
                f"""
                CREATE POLICY tenant_isolation ON {quoted}
                USING (
                    organization_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint
                )
                WITH CHECK (
                    organization_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint
                )
                """
            )


def disable_generic_rest_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in _TENANT_TABLES:
            quoted = schema_editor.quote_name(table)
            cursor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
            cursor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('documents', '0002_documentsetgrant_scenariodocumentsetbinding'),
        ('ingestion', '0007_confluencesyncrun_tenantconfluenceprofilegrant_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorSchedulePromotionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorSyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interval_seconds', models.PositiveIntegerField(default=86400)),
                ('enabled', models.BooleanField(default=False)),
                ('next_run_at', models.DateTimeField()),
                ('last_slot_at', models.DateTimeField(blank=True, null=True)),
                ('automation_mode', models.CharField(choices=[('draft_only', 'Draft only'), ('stage_only', 'Publish and build staged index'), ('promote_if_safe', 'Promote after existing gates pass')], default='draft_only', max_length=24)),
                ('configured_by', models.CharField(max_length=255)),
                ('promotion_approved_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestDocumentCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=256)),
                ('external_revision', models.CharField(blank=True, max_length=256)),
                ('content_checksum', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('active', 'Active'), ('missing', 'Missing')], default='active', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='RestPullContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('logical_id', models.CharField(max_length=128)),
                ('revision', models.PositiveIntegerField()),
                ('definition', models.JSONField()),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RestPullProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('logical_id', models.CharField(max_length=128)),
                ('revision', models.PositiveIntegerField()),
                ('scheme', models.CharField(default='https', max_length=8)),
                ('host', models.CharField(max_length=253)),
                ('port', models.PositiveIntegerField(default=443)),
                ('path_prefix', models.CharField(default='/', max_length=512)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST (read-only contract)')], default='GET', max_length=8)),
                ('auth_mode', models.CharField(choices=[('none', 'None'), ('bearer', 'Bearer'), ('api_key_header', 'API key header')], default='none', max_length=24)),
                ('secret_ref', models.CharField(blank=True, max_length=160)),
                ('api_key_header_name', models.CharField(blank=True, max_length=64)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_response_bytes', models.PositiveIntegerField(default=5000000)),
                ('max_total_bytes', models.PositiveBigIntegerField(default=100000000)),
                ('max_requests', models.PositiveIntegerField(default=1000)),
                ('max_items', models.PositiveIntegerField(default=50000)),
                ('max_pages', models.PositiveIntegerField(default=1000)),
                ('max_retries', models.PositiveSmallIntegerField(default=2)),
                ('max_decoded_item_bytes', models.PositiveIntegerField(default=25000000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('retry', 'Retry'), ('succeeded', 'Succeeded'), ('dead_letter', 'Dead letter')], default='queued', max_length=16)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('snapshot_complete', models.BooleanField(default=False)),
                ('material_change', models.BooleanField(default=False)),
                ('discovered_count', models.PositiveIntegerField(default=0)),
                ('changed_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('fetched_bytes', models.PositiveBigIntegerField(default=0)),
                ('schedule_slot', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantRestPullProfileGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='source',
            name='source_confluence_binding_consistent',
        ),
        migrations.AddField(
            model_name='confluencesyncrun',
            name='material_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confluencesyncrun',
            name='schedule_slot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexversion',
            name='embedded_chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexversion',
            name='embedded_document_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexversion',
            name='parent_index_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_index_versions', to='ingestion.indexversion'),
        ),
        migrations.AddField(
            model_name='indexversion',
            name='pipeline_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='indexversion',
            name='reused_chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexversion',
            name='reused_document_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='connector_type',
            field=models.CharField(choices=[('https', 'Allowlisted HTTPS'), ('s3', 'S3/MinIO object'), ('confluence_dc', 'Confluence Data Center'), ('generic_rest', 'Governed generic REST')], max_length=16),
        ),
        migrations.AddField(
            model_name='connectorschedulepromotiontarget',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_promotion_targets', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='connectorschedulepromotiontarget',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_promotion_targets', to='catalog.scenario'),
        ),
        migrations.AddField(
            model_name='connectorsyncschedule',
            name='embedding_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='connector_schedules', to='ingestion.embeddingprofile'),
        ),
        migrations.AddField(
            model_name='connectorsyncschedule',
            name='ocr_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='connector_schedules', to='ingestion.ocrprofile'),
        ),
        migrations.AddField(
            model_name='connectorsyncschedule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_sync_schedules', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='connectorsyncschedule',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_schedule', to='ingestion.source'),
        ),
        migrations.AddField(
            model_name='connectorschedulepromotiontarget',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_targets', to='ingestion.connectorsyncschedule'),
        ),
        migrations.AddField(
            model_name='confluencesyncrun',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confluence_runs', to='ingestion.connectorsyncschedule'),
        ),
        migrations.AddConstraint(
            model_name='confluencesyncrun',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False), ('schedule_slot__isnull', False)), fields=('schedule', 'schedule_slot'), name='uniq_confluence_schedule_slot'),
        ),
        migrations.AddField(
            model_name='restdocumentcursor',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_cursors', to='documents.document'),
        ),
        migrations.AddField(
            model_name='restdocumentcursor',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rest_cursors', to='documents.documentversion'),
        ),
        migrations.AddField(
            model_name='restdocumentcursor',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_document_cursors', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='restdocumentcursor',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_document_cursors', to='ingestion.source'),
        ),
        migrations.AddField(
            model_name='restpullcontract',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_pull_contracts', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='source',
            name='rest_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='ingestion.restpullcontract'),
        ),
        migrations.AddConstraint(
            model_name='restpullprofile',
            constraint=models.UniqueConstraint(fields=('logical_id', 'revision'), name='uniq_rest_profile_logical_revision'),
        ),
        migrations.AddField(
            model_name='source',
            name='rest_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='ingestion.restpullprofile'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confluence_profile__isnull', False), ('connector_type', 'confluence_dc'), ('document_set__isnull', False), ('rest_contract__isnull', True), ('rest_profile__isnull', True)), models.Q(models.Q(('connector_type', 'confluence_dc'), _negated=True), ('confluence_profile__isnull', True)), _connector='OR'), name='source_confluence_binding_consistent'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confluence_profile__isnull', True), ('connector_type', 'generic_rest'), ('document_set__isnull', False), ('rest_contract__isnull', False), ('rest_profile__isnull', False)), models.Q(models.Q(('connector_type', 'generic_rest'), _negated=True), ('rest_contract__isnull', True), ('rest_profile__isnull', True)), _connector='OR'), name='source_rest_binding_consistent'),
        ),
        migrations.AddField(
            model_name='restsyncrun',
            name='candidate_set_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_sync_runs', to='documents.documentsetversion'),
        ),
        migrations.AddField(
            model_name='restsyncrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_sync_runs', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='restsyncrun',
            name='rest_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_runs', to='ingestion.restpullcontract'),
        ),
        migrations.AddField(
            model_name='restsyncrun',
            name='rest_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_runs', to='ingestion.restpullprofile'),
        ),
        migrations.AddField(
            model_name='restsyncrun',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rest_runs', to='ingestion.connectorsyncschedule'),
        ),
        migrations.AddField(
            model_name='restsyncrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_sync_runs', to='ingestion.source'),
        ),
        migrations.AddField(
            model_name='restdocumentcursor',
            name='last_seen_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_cursors', to='ingestion.restsyncrun'),
        ),
        migrations.AddField(
            model_name='tenantrestpullprofilegrant',
            name='document_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_pull_profile_grants', to='documents.documentset'),
        ),
        migrations.AddField(
            model_name='tenantrestpullprofilegrant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_pull_profile_grants', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='tenantrestpullprofilegrant',
            name='rest_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_document_set_grants', to='ingestion.restpullprofile'),
        ),
        migrations.AddConstraint(
            model_name='connectorschedulepromotiontarget',
            constraint=models.UniqueConstraint(fields=('schedule', 'scenario'), name='uniq_connector_schedule_scenario'),
        ),
        migrations.AddConstraint(
            model_name='restpullcontract',
            constraint=models.UniqueConstraint(fields=('organization', 'logical_id', 'revision'), name='uniq_rest_contract_org_logical_revision'),
        ),
        migrations.AddConstraint(
            model_name='restsyncrun',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False), ('schedule_slot__isnull', False)), fields=('schedule', 'schedule_slot'), name='uniq_rest_schedule_slot'),
        ),
        migrations.AddConstraint(
            model_name='restdocumentcursor',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_rest_source_external_id'),
        ),
        migrations.AddConstraint(
            model_name='tenantrestpullprofilegrant',
            constraint=models.UniqueConstraint(fields=('organization', 'document_set', 'rest_profile'), name='uniq_tenant_docset_rest_grant'),
        ),
        migrations.RunPython(enable_generic_rest_rls, disable_generic_rest_rls),
    ]
