# Generated by Django 5.2.16 on 2026-07-13 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentsetgrant_scenariodocumentsetbinding'),
        ('ingestion', '0008_generic_rest_periodic_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorsyncschedule',
            name='automation_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='connectorsyncschedule',
            name='automation_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='idle', max_length=16),
        ),
        migrations.AddField(
            model_name='connectorsyncschedule',
            name='last_automation_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector_automation_schedules', to='documents.documentsetversion'),
        ),
    ]
