# Generated by Django 5.2.16 on 2026-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentsetgrant_scenariodocumentsetbinding'),
        ('ingestion', '0009_connector_automation_idempotency'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('connector_type__in', ['confluence_dc', 'generic_rest']), ('document_set__isnull', False)), models.Q(models.Q(('connector_type__in', ['confluence_dc', 'generic_rest']), _negated=True), ('document_set__isnull', True)), _connector='OR'), name='source_document_set_binding_consistent'),
        ),
    ]
