# Generated by Django 5.2.16 on 2026-07-16 16:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


def enable_build_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in ("ingestion_stagedindexbuildjob", "ingestion_stagedindexbuildoutbox"):
            quoted = schema_editor.quote_name(table)
            cursor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
            cursor.execute(
                f"""CREATE POLICY tenant_isolation ON {quoted}
                USING (agenthub_tenant_scope_contains(organization_id))
                WITH CHECK (agenthub_tenant_scope_contains(organization_id))"""
            )


def disable_build_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in ("ingestion_stagedindexbuildoutbox", "ingestion_stagedindexbuildjob"):
            quoted = schema_editor.quote_name(table)
            cursor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
            cursor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_public_ids_constrain"),
        ("ingestion", "0010_restore_source_document_set_constraint"),
        ("tenancy", "0002_force_tenant_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionWorkerHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("instance_id", models.UUIDField(unique=True)),
                ("queue_role", models.CharField(default="ingestion", max_length=32)),
                ("service_revision", models.CharField(max_length=64)),
                ("contract_revision", models.PositiveSmallIntegerField()),
                ("config_fingerprint", models.CharField(max_length=64)),
                ("last_seen_at", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("queue_role", "ingestion")),
                        name="worker_heartbeat_ingestion_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StagedIndexBuildJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("request_checksum", models.CharField(editable=False, max_length=64)),
                ("pipeline_fingerprint", models.CharField(editable=False, max_length=64)),
                ("requested_by", models.CharField(max_length=255)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dispatch_pending", "Dispatch pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("retry_wait", "Retry waiting"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("reconciliation_required", "Reconciliation required"),
                        ],
                        default="dispatch_pending",
                        max_length=32,
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("documents_completed", models.PositiveIntegerField(default=0)),
                ("chunks_completed", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("dispatch_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField(default=0)),
                (
                    "document_set_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="index_build_jobs",
                        to="documents.documentsetversion",
                    ),
                ),
                (
                    "embedding_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="index_build_jobs",
                        to="ingestion.embeddingprofile",
                    ),
                ),
                (
                    "ocr_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="index_build_jobs",
                        to="ingestion.ocrprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staged_index_build_jobs",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "result_index_version",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="build_job",
                        to="ingestion.indexversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StagedIndexBuildOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_checksum", models.CharField(editable=False, max_length=64)),
                ("available_at", models.DateTimeField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("publish_attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox",
                        to="ingestion.stagedindexbuildjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staged_index_build_outbox",
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="stagedindexbuildjob",
            constraint=models.UniqueConstraint(
                fields=("organization", "request_checksum"),
                name="uniq_staged_job_org_request_checksum",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedindexbuildjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "dispatch_pending",
                            "queued",
                            "running",
                            "retry_wait",
                            "reconciliation_required",
                        ],
                    )
                ),
                fields=(
                    "organization",
                    "document_set_version",
                    "embedding_profile",
                    "pipeline_fingerprint",
                ),
                name="uniq_active_staged_index_build",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedindexbuildjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gte", 1), ("max_attempts__lte", 10)),
                name="staged_job_max_attempts_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedindexbuildjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt__lte", models.F("max_attempts"))),
                name="staged_job_attempt_within_max",
            ),
        ),
        migrations.RunPython(enable_build_rls, disable_build_rls),
    ]
