# Generated by Django 5.2.17 on 2026-09-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0006_artifactversion_descriptions"),
        ("documents", "0010_active_document_set_version_constraint"),
        ("ingestion", "0015_index_store_ddl_functions"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stagedindexbuildjob",
            name="uniq_staged_job_org_request_checksum",
        ),
        migrations.AddConstraint(
            model_name="stagedindexbuildjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "dispatch_pending",
                            "queued",
                            "running",
                            "retry_wait",
                            "reconciliation_required",
                        ],
                    )
                ),
                fields=("organization", "request_checksum"),
                name="uniq_staged_job_org_request_checksum",
            ),
        ),
    ]
