# Generated by Django 5.2.17 on 2026-09-09 07:49

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_active_document_set_version_constraint"),
        ("ingestion", "0016_scope_staged_job_checksum_constraint_to_active_states"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexversion",
            name="storage_layout",
            field=models.CharField(
                choices=[("legacy", "Legacy"), ("shared_v1", "Shared v1")],
                default="legacy",
                db_default="legacy",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="indexversion",
            name="storage_state",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("open", "Open"),
                    ("sealed", "Sealed"),
                    ("retired", "Retired"),
                ],
                default="new",
                db_default="new",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SharedVectorChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                (
                    "chunk_kind",
                    models.CharField(
                        choices=[("content", "Content"), ("summary", "Summary")],
                        default="content",
                        max_length=16,
                    ),
                ),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField()),
                ("dimensions", models.PositiveIntegerField()),
                ("representation", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.documentversion",
                    ),
                ),
                (
                    "index_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shared_chunks",
                        to="ingestion.indexversion",
                    ),
                ),
                (
                    "indexed_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.indexeddocument",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "index_version", "document_version"],
                        name="shared_chunk_scope",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("document_version__isnull", False),
                                ("indexed_document__isnull", True),
                            ),
                            models.Q(
                                ("document_version__isnull", True),
                                ("indexed_document__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="shared_chunk_exact_document",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("dimensions__in", [64, 768, 1536]),
                                ("representation", "vector"),
                            ),
                            models.Q(
                                ("dimensions__in", [3072, 4000]),
                                ("representation", "halfvec"),
                            ),
                            _connector="OR",
                        ),
                        name="shared_chunk_geometry",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("chunk_kind__in", ["content", "summary"])),
                        name="shared_chunk_kind",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("document_version__isnull", False)),
                        fields=(
                            "index_version",
                            "document_version",
                            "ordinal",
                            "chunk_kind",
                        ),
                        name="shared_chunk_managed_identity",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("indexed_document__isnull", False)),
                        fields=(
                            "index_version",
                            "indexed_document",
                            "ordinal",
                            "chunk_kind",
                        ),
                        name="shared_chunk_legacy_identity",
                    ),
                ],
            },
        ),
    ]
