# Generated by Django 5.2.17 on 2026-09-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0006_artifactversion_descriptions"),
        ("documents", "0010_active_document_set_version_constraint"),
        ("ingestion", "0018_shared_vector_integrity"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexversion",
            name="build_attempt",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indexversion",
            name="build_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempt_generations",
                to="ingestion.stagedindexbuildjob",
            ),
        ),
        migrations.AddConstraint(
            model_name="indexversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("build_request__isnull", False)),
                fields=("build_request", "build_attempt"),
                name="uniq_index_build_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="indexversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("build_attempt__isnull", True), ("build_request__isnull", True)),
                    models.Q(
                        ("build_attempt__gt", 0),
                        ("build_attempt__isnull", False),
                        ("build_request__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="index_build_attempt_binding",
            ),
        ),
    ]
