# Generated by Django 5.2.17 on 2026-09-10 06:21

import hashlib
import json
import uuid

import django.db.models.deletion
from django.db import migrations, models

_REST_FIELDS = (
    "logical_id",
    "revision",
    "scheme",
    "host",
    "port",
    "path_prefix",
    "method",
    "auth_mode",
    "secret_ref",
    "api_key_header_name",
    "timeout_seconds",
    "max_response_bytes",
    "max_total_bytes",
    "max_requests",
    "max_items",
    "max_pages",
    "max_retries",
    "max_decoded_item_bytes",
)
_CONFLUENCE_FIELDS = (
    "logical_id",
    "revision",
    "provider",
    "scheme",
    "host",
    "port",
    "context_path",
    "secret_ref",
    "network_policy_id",
    "timeout_seconds",
    "page_size",
    "max_pages",
    "max_depth",
    "max_requests",
    "max_retries",
    "max_response_bytes",
    "max_page_body_bytes",
    "max_total_bytes",
)


def map_existing_profiles(apps, schema_editor):
    Connection = apps.get_model("ingestion", "Connection")
    alias = schema_editor.connection.alias
    for model_name, kind, relation, field_names in (
        ("RestPullProfile", "rest_pull", "rest_profile_id", _REST_FIELDS),
        ("ConfluenceProfile", "confluence_dc", "confluence_profile_id", _CONFLUENCE_FIELDS),
    ):
        Profile = apps.get_model("ingestion", model_name)
        for profile in Profile.objects.using(alias).order_by("pk").iterator(chunk_size=200):
            payload = {name: getattr(profile, name) for name in field_names}
            body = {"contract": "connection-profile/v1", "kind": kind, "config": payload}
            checksum = hashlib.sha256(
                json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode(
                    "utf-8"
                )
            ).hexdigest()
            item, _ = Connection.objects.using(alias).get_or_create(
                **{relation: profile.pk},
                defaults={
                    "kind": kind,
                    "logical_id": profile.logical_id,
                    "revision": profile.revision,
                    "profile_checksum": checksum,
                    "created_by": "connection-identity-migration",
                },
            )
            if (item.kind, item.logical_id, item.revision, item.profile_checksum) != (
                kind,
                profile.logical_id,
                profile.revision,
                checksum,
            ):
                raise ValueError("CONNECTION_MIGRATION_PROFILE_MISMATCH")


_SQL = r"""
CREATE FUNCTION public.agenthub_connection_identity_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
DECLARE profile record;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'CONNECTION_IMMUTABLE';
    END IF;
    IF NEW.kind = 'rest_pull' THEN
        SELECT logical_id, revision INTO profile FROM public.ingestion_restpullprofile
        WHERE id = NEW.rest_profile_id FOR SHARE;
    ELSIF NEW.kind = 'confluence_dc' THEN
        SELECT logical_id, revision INTO profile FROM public.ingestion_confluenceprofile
        WHERE id = NEW.confluence_profile_id FOR SHARE;
    ELSE
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'CONNECTION_KIND_INVALID';
    END IF;
    IF NOT FOUND OR NEW.logical_id IS DISTINCT FROM profile.logical_id
       OR NEW.revision IS DISTINCT FROM profile.revision
       OR NEW.profile_checksum !~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'CONNECTION_PROFILE_MISMATCH';
    END IF;
    RETURN NEW;
END
$body$;
CREATE TRIGGER connection_identity_guard BEFORE INSERT OR UPDATE OR DELETE
ON public.ingestion_connection FOR EACH ROW
EXECUTE FUNCTION public.agenthub_connection_identity_guard();

CREATE FUNCTION public.agenthub_connection_profile_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
BEGIN
    IF EXISTS (
        SELECT 1 FROM public.ingestion_connection c WHERE
        (TG_TABLE_NAME = 'ingestion_restpullprofile' AND c.rest_profile_id = OLD.id)
        OR (TG_TABLE_NAME = 'ingestion_confluenceprofile' AND c.confluence_profile_id = OLD.id)
    ) AND (TG_OP = 'DELETE' OR (to_jsonb(NEW) - 'status') IS DISTINCT FROM
                               (to_jsonb(OLD) - 'status')) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'CONNECTION_PROFILE_IMMUTABLE';
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END
$body$;
CREATE TRIGGER connection_rest_profile_guard BEFORE UPDATE OR DELETE
ON public.ingestion_restpullprofile FOR EACH ROW
EXECUTE FUNCTION public.agenthub_connection_profile_guard();
CREATE TRIGGER connection_confluence_profile_guard BEFORE UPDATE OR DELETE
ON public.ingestion_confluenceprofile FOR EACH ROW
EXECUTE FUNCTION public.agenthub_connection_profile_guard();

CREATE FUNCTION public.agenthub_source_connection_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
DECLARE identity record;
BEGIN
    IF NEW.connection_id IS NULL THEN
        IF TG_OP = 'UPDATE' AND OLD.connection_id IS NOT NULL THEN
            RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'SOURCE_CONNECTION_DOWNGRADE';
        END IF;
        RETURN NEW;
    END IF;
    SELECT * INTO identity FROM public.ingestion_connection WHERE id = NEW.connection_id;
    IF NOT FOUND OR NOT (
        (NEW.connector_type = 'generic_rest' AND identity.kind = 'rest_pull'
         AND NEW.rest_profile_id IS NOT DISTINCT FROM identity.rest_profile_id)
        OR (NEW.connector_type = 'confluence_dc' AND identity.kind = 'confluence_dc'
            AND NEW.confluence_profile_id IS NOT DISTINCT FROM identity.confluence_profile_id)
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'SOURCE_CONNECTION_MISMATCH';
    END IF;
    RETURN NEW;
END
$body$;
CREATE TRIGGER source_connection_guard BEFORE INSERT OR UPDATE ON public.ingestion_source
FOR EACH ROW EXECUTE FUNCTION public.agenthub_source_connection_guard();
"""


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_SQL)


def remove_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("""
            DROP TRIGGER source_connection_guard ON public.ingestion_source;
            DROP FUNCTION public.agenthub_source_connection_guard();
            DROP TRIGGER connection_rest_profile_guard ON public.ingestion_restpullprofile;
            DROP TRIGGER connection_confluence_profile_guard ON public.ingestion_confluenceprofile;
            DROP FUNCTION public.agenthub_connection_profile_guard();
            DROP TRIGGER connection_identity_guard ON public.ingestion_connection;
            DROP FUNCTION public.agenthub_connection_identity_guard();
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0020_shared_build_attempt_integrity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("rest_pull", "REST veri bağlantısı"),
                            ("confluence_dc", "Confluence veri bağlantısı"),
                        ],
                        max_length=24,
                    ),
                ),
                ("logical_id", models.CharField(max_length=128)),
                ("revision", models.PositiveIntegerField()),
                ("profile_checksum", models.CharField(editable=False, max_length=64)),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confluence_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connection_identity",
                        to="ingestion.confluenceprofile",
                    ),
                ),
                (
                    "rest_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connection_identity",
                        to="ingestion.restpullprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="source",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sources",
                to="ingestion.connection",
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.UniqueConstraint(
                fields=("kind", "logical_id", "revision"),
                name="uniq_connection_kind_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("kind", "rest_pull"),
                        ("rest_profile__isnull", False),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", False),
                        ("kind", "confluence_dc"),
                        ("rest_profile__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="connection_profile_kind_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="connection_revision_positive",
            ),
        ),
        migrations.RunPython(map_existing_profiles, migrations.RunPython.noop),
        migrations.RunPython(install_guards, remove_guards),
    ]
