# Generated by Django 5.2.17 on 2026-09-10 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0006_artifactversion_descriptions"),
        ("documents", "0011_explicit_shared_data_access"),
        ("ingestion", "0021_connection_identity"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedindexbuildjob",
            name="confluence_sync_run",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingestion_job",
                to="ingestion.confluencesyncrun",
            ),
        ),
        migrations.AddField(
            model_name="stagedindexbuildjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("index_build", "Veri hazırlama"),
                    ("rest_sync", "REST veri yenileme"),
                    ("confluence_sync", "Confluence veri yenileme"),
                ],
                db_default="index_build",
                default="index_build",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="stagedindexbuildjob",
            name="rest_sync_run",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingestion_job",
                to="ingestion.restsyncrun",
            ),
        ),
        migrations.AddField(
            model_name="stagedindexbuildjob",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingestion_jobs",
                to="ingestion.source",
            ),
        ),
        migrations.AddField(
            model_name="stagedindexbuildjob",
            name="source_config_checksum",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name="stagedindexbuildjob",
            name="document_set_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="index_build_jobs",
                to="documents.documentsetversion",
            ),
        ),
        migrations.AlterField(
            model_name="stagedindexbuildjob",
            name="embedding_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="index_build_jobs",
                to="ingestion.embeddingprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedindexbuildjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confluence_sync_run__isnull", True),
                        ("document_set_version__isnull", False),
                        ("embedding_profile__isnull", False),
                        ("kind", "index_build"),
                        ("rest_sync_run__isnull", True),
                        ("source__isnull", True),
                        ("source_config_checksum", ""),
                    ),
                    models.Q(
                        ("chunking_profile__isnull", True),
                        ("document_set_version__isnull", True),
                        ("embedding_profile__isnull", True),
                        ("ocr_profile__isnull", True),
                        ("result_index_version__isnull", True),
                        ("retrieval_profile__isnull", True),
                        ("source__isnull", False),
                        ("source_config_checksum__regex", "^[0-9a-f]{64}$"),
                        ("summary_model_profile__isnull", True),
                        ("summary_prompt_contract__isnull", True),
                        models.Q(
                            models.Q(
                                ("confluence_sync_run__isnull", True),
                                ("kind", "rest_sync"),
                                ("rest_sync_run__isnull", False),
                            ),
                            models.Q(
                                ("confluence_sync_run__isnull", False),
                                ("kind", "confluence_sync"),
                                ("rest_sync_run__isnull", True),
                            ),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="ingestion_job_typed_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedindexbuildjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source__isnull", False),
                    (
                        "status__in",
                        [
                            "dispatch_pending",
                            "queued",
                            "running",
                            "retry_wait",
                            "reconciliation_required",
                        ],
                    ),
                ),
                fields=("source",),
                name="uniq_active_ingestion_source_job",
            ),
        ),
    ]
