# Generated by Django 5.2.17 on 2026-09-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0023_ingestion_job_authority"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedindexbuildoutbox",
            name="completion_available_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stagedindexbuildoutbox",
            name="completion_error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="stagedindexbuildoutbox",
            name="completion_publish_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stagedindexbuildoutbox",
            name="completion_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
