# Generated by Django 5.2.17 on 2026-09-10 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_explicit_shared_data_access"),
        ("ingestion", "0025_protect_selected_legacy_store"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="McpResourceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("logical_id", models.CharField(max_length=128)),
                ("revision", models.PositiveIntegerField()),
                (
                    "protocol_version",
                    models.CharField(default="2025-06-18", max_length=16),
                ),
                ("destination", models.JSONField()),
                ("resource_prefixes", models.JSONField()),
                ("mime_types", models.JSONField()),
                ("limits", models.JSONField(blank=True, default=dict)),
                ("secret_ref", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TenantMcpResourceGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="connection",
            name="connection_profile_kind_consistent",
        ),
        migrations.RemoveConstraint(
            model_name="source",
            name="source_document_set_binding_consistent",
        ),
        migrations.AlterField(
            model_name="connection",
            name="kind",
            field=models.CharField(
                choices=[
                    ("rest_pull", "REST veri bağlantısı"),
                    ("confluence_dc", "Confluence veri bağlantısı"),
                    ("mcp_resource", "MCP belge bağlantısı"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="connector_type",
            field=models.CharField(
                choices=[
                    ("https", "Allowlisted HTTPS"),
                    ("s3", "S3/MinIO object"),
                    ("confluence_dc", "Confluence Data Center"),
                    ("generic_rest", "Governed generic REST"),
                    ("mcp_resource", "MCP belge kaynağı"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "connector_type__in",
                            ["confluence_dc", "generic_rest", "mcp_resource"],
                        ),
                        ("document_set__isnull", False),
                    ),
                    models.Q(
                        models.Q(
                            (
                                "connector_type__in",
                                ["confluence_dc", "generic_rest", "mcp_resource"],
                            ),
                            _negated=True,
                        ),
                        ("document_set__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="source_document_set_binding_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("connector_type", "mcp_resource"), _negated=True),
                    models.Q(
                        ("connection__isnull", False), ("document_set__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="source_mcp_binding_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="mcpresourceprofile",
            constraint=models.UniqueConstraint(
                fields=("logical_id", "revision"), name="uniq_mcp_resource_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="mcpresourceprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="mcp_resource_revision_positive",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="mcp_resource_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connection_identity",
                to="ingestion.mcpresourceprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("kind", "rest_pull"),
                        ("mcp_resource_profile__isnull", True),
                        ("rest_profile__isnull", False),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", False),
                        ("kind", "confluence_dc"),
                        ("mcp_resource_profile__isnull", True),
                        ("rest_profile__isnull", True),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("kind", "mcp_resource"),
                        ("mcp_resource_profile__isnull", False),
                        ("rest_profile__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="connection_profile_kind_consistent",
            ),
        ),
        migrations.AddField(
            model_name="tenantmcpresourcegrant",
            name="document_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="documents.documentset"
            ),
        ),
        migrations.AddField(
            model_name="tenantmcpresourcegrant",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
            ),
        ),
        migrations.AddField(
            model_name="tenantmcpresourcegrant",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ingestion.mcpresourceprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmcpresourcegrant",
            constraint=models.UniqueConstraint(
                fields=("organization", "document_set", "profile"),
                name="uniq_mcp_resource_grant",
            ),
        ),
    ]
