# Generated by Django 5.2.17 on 2026-09-10 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0006_artifactversion_descriptions"),
        ("documents", "0011_explicit_shared_data_access"),
        ("ingestion", "0027_mcp_resource_authority"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="resource_snapshot",
                        serialize=False,
                        to="ingestion.stagedindexbuildjob",
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=0)),
                ("snapshot_complete", models.BooleanField(default=False)),
                ("material_change", models.BooleanField(default=False)),
                ("discovered_count", models.PositiveIntegerField(default=0)),
                ("changed_count", models.PositiveIntegerField(default=0)),
                ("unchanged_count", models.PositiveIntegerField(default=0)),
                ("missing_count", models.PositiveIntegerField(default=0)),
                ("fetched_bytes", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceDocumentCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=2048)),
                ("external_id_hash", models.CharField(max_length=64)),
                ("content_checksum", models.CharField(max_length=64)),
                ("last_seen_attempt", models.PositiveSmallIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Active"), ("missing", "Missing")],
                        default="active",
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="stagedindexbuildjob",
            name="ingestion_job_typed_target",
        ),
        migrations.AlterField(
            model_name="stagedindexbuildjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("index_build", "Veri hazırlama"),
                    ("rest_sync", "REST veri yenileme"),
                    ("confluence_sync", "Confluence veri yenileme"),
                    ("mcp_resource_sync", "MCP belge yenileme"),
                ],
                db_default="index_build",
                default="index_build",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedindexbuildjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confluence_sync_run__isnull", True),
                        ("document_set_version__isnull", False),
                        ("embedding_profile__isnull", False),
                        ("kind", "index_build"),
                        ("rest_sync_run__isnull", True),
                        ("source__isnull", True),
                        ("source_config_checksum", ""),
                    ),
                    models.Q(
                        ("chunking_profile__isnull", True),
                        ("document_set_version__isnull", True),
                        ("embedding_profile__isnull", True),
                        ("ocr_profile__isnull", True),
                        ("result_index_version__isnull", True),
                        ("retrieval_profile__isnull", True),
                        ("source__isnull", False),
                        ("source_config_checksum__regex", "^[0-9a-f]{64}$"),
                        ("summary_model_profile__isnull", True),
                        ("summary_prompt_contract__isnull", True),
                        models.Q(
                            models.Q(
                                ("confluence_sync_run__isnull", True),
                                ("kind", "rest_sync"),
                                ("rest_sync_run__isnull", False),
                            ),
                            models.Q(
                                ("confluence_sync_run__isnull", False),
                                ("kind", "confluence_sync"),
                                ("rest_sync_run__isnull", True),
                            ),
                            models.Q(
                                ("confluence_sync_run__isnull", True),
                                ("kind", "mcp_resource_sync"),
                                ("rest_sync_run__isnull", True),
                            ),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="ingestion_job_typed_target",
            ),
        ),
        migrations.AddField(
            model_name="resourcesnapshot",
            name="candidate_set_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.documentsetversion",
            ),
        ),
        migrations.AddField(
            model_name="resourcesnapshot",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
            ),
        ),
        migrations.AddField(
            model_name="sourcedocumentcursor",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="documents.document"
            ),
        ),
        migrations.AddField(
            model_name="sourcedocumentcursor",
            name="document_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.documentversion",
            ),
        ),
        migrations.AddField(
            model_name="sourcedocumentcursor",
            name="last_seen_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ingestion.stagedindexbuildjob",
            ),
        ),
        migrations.AddField(
            model_name="sourcedocumentcursor",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tenancy.organization"
            ),
        ),
        migrations.AddField(
            model_name="sourcedocumentcursor",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resource_cursors",
                to="ingestion.source",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcedocumentcursor",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id_hash"),
                name="uniq_source_resource_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcedocumentcursor",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["active", "missing"])),
                name="resource_cursor_state_valid",
            ),
        ),
    ]
