# Generated by Django 5.2.17 on 2026-09-10 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


SQL = r"""
CREATE FUNCTION public.agenthub_rest_setup_draft_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF (NEW.public_id, NEW.organization_id, NEW.document_set_id, NEW.owner_id,
            NEW.created_at, NEW.expires_at) IS DISTINCT FROM
           (OLD.public_id, OLD.organization_id, OLD.document_set_id, OLD.owner_id,
            OLD.created_at, OLD.expires_at) OR OLD.completed_source_id IS NOT NULL THEN
            RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'REST_SETUP_DRAFT_BINDING_IMMUTABLE';
        END IF;
        IF NEW.revision <> OLD.revision + 1 THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'REST_SETUP_DRAFT_REVISION_INVALID';
        END IF;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.documents_documentset d
        WHERE d.id = NEW.document_set_id AND d.organization_id = NEW.organization_id) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'REST_SETUP_DRAFT_SCOPE_INVALID';
    END IF;
    IF jsonb_typeof(NEW.payload) <> 'object' OR octet_length(NEW.payload::text) > 160000
       OR (NEW.payload - ARRAY['name','step','mode','profile','definition','inputs','schedule']) <> '{}'::jsonb THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'REST_SETUP_DRAFT_PAYLOAD_INVALID';
    END IF;
    IF NEW.completed_source_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.ingestion_source s WHERE s.id = NEW.completed_source_id
        AND s.organization_id = NEW.organization_id AND s.document_set_id = NEW.document_set_id
        AND s.connector_type = 'generic_rest'
        AND s.slug = 'rest-' || replace(NEW.public_id::text, '-', '')
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'REST_SETUP_DRAFT_SOURCE_INVALID';
    END IF;
    RETURN NEW;
END
$body$;
CREATE TRIGGER rest_setup_draft_guard BEFORE INSERT OR UPDATE
ON public.ingestion_restsetupdraft FOR EACH ROW
EXECUTE FUNCTION public.agenthub_rest_setup_draft_guard();
ALTER TABLE public.ingestion_restsetupdraft ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingestion_restsetupdraft FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ingestion_restsetupdraft
USING (public.agenthub_tenant_scope_contains(organization_id))
WITH CHECK (public.agenthub_tenant_scope_contains(organization_id));
"""


def install(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(SQL, params=None)


def reverse(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        # A FORCE-RLS table may look empty to its owner under a restricted scope.
        # Refuse reversal unless the emptiness query can see every tenant.
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT rolsuper OR rolbypassrls FROM pg_roles WHERE rolname = current_user")
            role = cursor.fetchone()
        if not role or not role[0]:
            raise RuntimeError("REST_SETUP_DRAFT_ROLLBACK_REQUIRES_PRIVILEGED_ROLE")
    if apps.get_model("ingestion", "RestSetupDraft").objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError("REST_SETUP_DRAFT_ROLLBACK_REQUIRES_EMPTY_TABLE")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("""
            DROP TRIGGER rest_setup_draft_guard ON public.ingestion_restsetupdraft;
            DROP FUNCTION public.agenthub_rest_setup_draft_guard();
            DROP POLICY tenant_isolation ON public.ingestion_restsetupdraft;
            ALTER TABLE public.ingestion_restsetupdraft NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE public.ingestion_restsetupdraft DISABLE ROW LEVEL SECURITY;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_explicit_shared_data_access"),
        ("ingestion", "0029_resource_snapshot_authority"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RestSetupDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("payload", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("expires_at", models.DateTimeField()),
                (
                    "completed_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.source",
                    ),
                ),
                (
                    "document_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.documentset",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "owner", "expires_at"],
                        name="rest_draft_owner_expiry",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="rest_draft_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("completed_source__isnull", True),
                            ("payload", {}),
                            _connector="OR",
                        ),
                        name="rest_draft_completed_payload_empty",
                    ),
                ],
            },
        ),
        migrations.RunPython(install, reverse),
    ]
