# Generated by Django 5.2.17 on 2026-09-10 11:33

import django.db.models.deletion
from django.db import migrations, models


SQL = r"""
CREATE FUNCTION public.agenthub_source_preparation_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
DECLARE evidence record; target record;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF OLD.preparation_job_id IS NOT NULL AND
           NEW.preparation_job_id IS DISTINCT FROM OLD.preparation_job_id THEN
            RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'INGESTION_PREPARATION_LINK_IMMUTABLE';
        END IF;
        IF OLD.kind = 'index_build' AND ROW(
            NEW.organization_id, NEW.document_set_version_id, NEW.embedding_profile_id,
            NEW.ocr_profile_id, NEW.chunking_profile_id, NEW.retrieval_profile_id,
            NEW.summary_model_profile_id, NEW.summary_prompt_contract_id,
            NEW.request_checksum, NEW.pipeline_fingerprint
        ) IS DISTINCT FROM ROW(
            OLD.organization_id, OLD.document_set_version_id, OLD.embedding_profile_id,
            OLD.ocr_profile_id, OLD.chunking_profile_id, OLD.retrieval_profile_id,
            OLD.summary_model_profile_id, OLD.summary_prompt_contract_id,
            OLD.request_checksum, OLD.pipeline_fingerprint
        ) AND EXISTS (SELECT 1 FROM public.ingestion_stagedindexbuildjob p
                      WHERE p.preparation_job_id = OLD.id) THEN
            RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'INGESTION_PREPARATION_TARGET_IMMUTABLE';
        END IF;
    END IF;
    IF NEW.preparation_job_id IS NULL THEN RETURN NEW; END IF;
    IF NEW.status <> 'succeeded' OR NEW.kind NOT IN ('rest_sync','confluence_sync','mcp_resource_sync') THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'INGESTION_PREPARATION_PARENT_INVALID';
    END IF;
    IF NEW.kind = 'rest_sync' THEN
        SELECT organization_id, snapshot_complete, candidate_set_version_id INTO evidence
        FROM public.ingestion_restsyncrun WHERE id = NEW.rest_sync_run_id;
    ELSIF NEW.kind = 'confluence_sync' THEN
        SELECT organization_id, snapshot_complete, candidate_set_version_id INTO evidence
        FROM public.ingestion_confluencesyncrun WHERE id = NEW.confluence_sync_run_id;
    ELSE
        SELECT organization_id, snapshot_complete, candidate_set_version_id INTO evidence
        FROM public.ingestion_resourcesnapshot WHERE job_id = NEW.id;
    END IF;
    IF NOT FOUND OR evidence.organization_id <> NEW.organization_id OR NOT evidence.snapshot_complete
       OR evidence.candidate_set_version_id IS NULL THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'INGESTION_PREPARATION_SNAPSHOT_INVALID';
    END IF;
    SELECT * INTO target FROM public.ingestion_stagedindexbuildjob
    WHERE id = NEW.preparation_job_id FOR SHARE;
    IF NOT FOUND OR target.kind <> 'index_build' OR target.organization_id <> NEW.organization_id
       OR target.document_set_version_id IS DISTINCT FROM evidence.candidate_set_version_id THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'INGESTION_PREPARATION_TARGET_INVALID';
    END IF;
    RETURN NEW;
END
$body$;
CREATE TRIGGER source_preparation_guard BEFORE INSERT OR UPDATE
ON public.ingestion_stagedindexbuildjob FOR EACH ROW
EXECUTE FUNCTION public.agenthub_source_preparation_guard();
"""


def install(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(SQL, params=None)


def reverse(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT rolsuper OR rolbypassrls FROM pg_roles WHERE rolname = current_user")
            role = cursor.fetchone()
        if not role or not role[0]:
            raise RuntimeError("PREPARATION_LINK_ROLLBACK_REQUIRES_PRIVILEGED_ROLE")
    if apps.get_model("ingestion", "StagedIndexBuildJob").objects.using(schema_editor.connection.alias).filter(preparation_job__isnull=False).exists():
        raise RuntimeError("PREPARATION_LINK_ROLLBACK_REQUIRES_NO_LINKS")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("""
            DROP TRIGGER source_preparation_guard ON public.ingestion_stagedindexbuildjob;
            DROP FUNCTION public.agenthub_source_preparation_guard();
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0006_artifactversion_descriptions"),
        ("documents", "0011_explicit_shared_data_access"),
        ("ingestion", "0030_rest_setup_draft"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedindexbuildjob",
            name="preparation_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_jobs",
                to="ingestion.stagedindexbuildjob",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedindexbuildjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("preparation_job__isnull", True),
                    models.Q(("kind", "index_build"), _negated=True),
                    _connector="OR",
                ),
                name="ingestion_preparation_parent_kind",
            ),
        ),
        migrations.RunPython(install, reverse),
    ]
