# Generated by Django 5.2.17 on 2026-09-11 06:37

import django.db.models.deletion
from importlib import import_module
from django.db import migrations, models


def previous_guard():
    sql = import_module("apps.ingestion.migrations.0029_resource_snapshot_authority").SQL
    return (sql.split("$body$;", 1)[0] + "$body$;").replace(
        "CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1
    )


SCHEDULE_SQL = r"""
CREATE FUNCTION public.agenthub_mcp_schedule_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
DECLARE src record;
BEGIN
    IF TG_OP = 'UPDATE' AND (NEW.source_id, NEW.organization_id)
       IS DISTINCT FROM (OLD.source_id, OLD.organization_id) AND (
           EXISTS (SELECT 1 FROM public.ingestion_resourcesnapshot r WHERE r.schedule_id = OLD.id)
           OR EXISTS (SELECT 1 FROM public.ingestion_source s
                      WHERE s.id = OLD.source_id AND s.connector_type = 'mcp_resource')
       ) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'RESOURCE_SCHEDULE_BINDING_IMMUTABLE';
    END IF;
    SELECT * INTO src FROM public.ingestion_source WHERE id = NEW.source_id;
    IF FOUND AND src.connector_type = 'mcp_resource' AND (
        src.organization_id <> NEW.organization_id
        OR NEW.automation_mode NOT IN ('draft_only', 'stage_only')
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'RESOURCE_SCHEDULE_SCOPE_INVALID';
    END IF;
    RETURN NEW;
END
$body$;
CREATE TRIGGER mcp_schedule_guard BEFORE INSERT OR UPDATE
ON public.ingestion_connectorsyncschedule FOR EACH ROW
EXECUTE FUNCTION public.agenthub_mcp_schedule_guard();
"""


def install(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    sql = previous_guard().replace(
        "(NEW.job_id, NEW.organization_id) IS DISTINCT FROM (OLD.job_id, OLD.organization_id)",
        "(NEW.job_id, NEW.organization_id, NEW.schedule_id, NEW.schedule_slot) IS DISTINCT FROM "
        "(OLD.job_id, OLD.organization_id, OLD.schedule_id, OLD.schedule_slot)",
    )
    sql = sql.replace("    IF TG_OP = 'INSERT' THEN", r"""
    IF NEW.schedule_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.ingestion_connectorsyncschedule c
        JOIN public.ingestion_source s ON s.id = c.source_id
        WHERE c.id = NEW.schedule_id AND c.organization_id = NEW.organization_id
        AND c.source_id = owner.source_id AND s.connector_type = 'mcp_resource'
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'RESOURCE_SNAPSHOT_SCHEDULE_INVALID';
    END IF;
    IF TG_OP = 'INSERT' THEN""", 1)
    schema_editor.execute(sql + SCHEDULE_SQL, params=None)


def reverse(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT rolsuper OR rolbypassrls FROM pg_roles WHERE rolname = current_user")
            role = cursor.fetchone()
        if not role or not role[0]:
            raise RuntimeError("RESOURCE_SCHEDULE_ROLLBACK_REQUIRES_PRIVILEGED_ROLE")
    if apps.get_model("ingestion", "ResourceSnapshot").objects.using(schema_editor.connection.alias).filter(schedule__isnull=False).exists():
        raise RuntimeError("RESOURCE_SCHEDULE_ROLLBACK_REQUIRES_EMPTY_HISTORY")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(previous_guard() + """
            DROP TRIGGER mcp_schedule_guard ON public.ingestion_connectorsyncschedule;
            DROP FUNCTION public.agenthub_mcp_schedule_guard();
        """, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_explicit_shared_data_access"),
        ("ingestion", "0031_source_preparation_link"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcesnapshot",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resource_runs",
                to="ingestion.connectorsyncschedule",
            ),
        ),
        migrations.AddField(
            model_name="resourcesnapshot",
            name="schedule_slot",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="resourcesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("schedule__isnull", True), ("schedule_slot__isnull", True)
                    ),
                    models.Q(
                        ("schedule__isnull", False), ("schedule_slot__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="mcp_snapshot_schedule_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcesnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("schedule__isnull", False)),
                fields=("schedule", "schedule_slot"),
                name="mcp_snapshot_schedule_slot_unique",
            ),
        ),
        migrations.RunPython(install, reverse),
    ]
