# Generated by Django 5.2.17 on 2026-09-11 07:40

from importlib import import_module

import django.db.models.deletion
from django.db import migrations, models

SQL = r"""
CREATE FUNCTION public.agenthub_source_revision_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
DECLARE root record; item record;
BEGIN
    IF TG_OP = 'DELETE' OR (TG_OP = 'UPDATE' AND
       (to_jsonb(NEW) - 'is_current') IS DISTINCT FROM (to_jsonb(OLD) - 'is_current')) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'SOURCE_REVISION_IMMUTABLE';
    END IF;
    SELECT * INTO root FROM public.ingestion_source WHERE id = NEW.root_source_id FOR SHARE;
    SELECT * INTO item FROM public.ingestion_source WHERE id = NEW.source_id FOR SHARE;
    IF root.id IS NULL OR item.id IS NULL OR root.organization_id <> NEW.organization_id
       OR item.organization_id <> NEW.organization_id OR root.connector_type <> 'generic_rest'
       OR item.connector_type <> 'generic_rest' OR root.document_set_id <> item.document_set_id
       OR NEW.checksum !~ '^[0-9a-f]{64}$'
       OR (NEW.number = 1) IS DISTINCT FROM (NEW.root_source_id = NEW.source_id)
       OR (NEW.number > 1 AND NEW.base_token !~ '^[0-9a-f]{64}$') THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'SOURCE_REVISION_SCOPE_INVALID';
    END IF;
    IF NEW.schedule_config IS NOT NULL AND (
       jsonb_typeof(NEW.schedule_config) <> 'object'
       OR (NEW.schedule_config - ARRAY['interval_seconds','preparation']) <> '{}'::jsonb
       OR NOT (NEW.schedule_config ? 'interval_seconds')
       OR jsonb_typeof(NEW.schedule_config->'interval_seconds') <> 'number'
       OR (NEW.schedule_config->>'interval_seconds') !~ '^[0-9]{3,6}$'
       OR (NEW.schedule_config->>'interval_seconds')::int < 60
       OR (NEW.schedule_config ? 'preparation' AND (
           jsonb_typeof(NEW.schedule_config->'preparation') <> 'string' OR
           (NEW.schedule_config->>'preparation') !~ '^[0-9a-f]{64}$'))) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'SOURCE_REVISION_SCHEDULE_INVALID';
    END IF;
    RETURN NEW;
END
$body$;
CREATE TRIGGER source_revision_guard BEFORE INSERT OR UPDATE OR DELETE
ON public.ingestion_sourceconfigurationrevision FOR EACH ROW
EXECUTE FUNCTION public.agenthub_source_revision_guard();

CREATE FUNCTION public.agenthub_source_revision_family_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.ingestion_sourceconfigurationrevision r
        WHERE r.root_source_id = NEW.root_source_id AND r.source_id = NEW.root_source_id
        AND r.number = 1 AND r.organization_id = NEW.organization_id)
       OR (SELECT count(*) FROM public.ingestion_sourceconfigurationrevision r
           WHERE r.root_source_id = NEW.root_source_id AND r.is_current) <> 1 THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'SOURCE_REVISION_FAMILY_INVALID';
    END IF;
    IF NEW.is_current AND EXISTS (
        SELECT 1 FROM public.ingestion_sourceconfigurationrevision r
        WHERE r.id = NEW.id AND r.is_current
    ) AND ((TG_OP = 'INSERT' AND NEW.number > 1)
                           OR (TG_OP = 'UPDATE' AND NOT OLD.is_current)) THEN
        IF NOT EXISTS (
            SELECT 1 FROM public.ingestion_stagedindexbuildjob j
            JOIN public.ingestion_restsyncrun r ON r.id = j.rest_sync_run_id
            JOIN public.ingestion_stagedindexbuildjob b ON b.id = j.preparation_job_id
            JOIN public.ingestion_indexversion i ON i.id = b.result_index_version_id
            WHERE j.source_id = NEW.source_id AND j.organization_id = NEW.organization_id
              AND j.status = 'succeeded' AND j.source_config_checksum = NEW.checksum
              AND r.snapshot_complete AND r.status = 'succeeded' AND b.status = 'succeeded'
              AND r.candidate_set_version_id = b.document_set_version_id
              AND i.document_set_version_id = b.document_set_version_id AND i.status = 'active'
              AND i.store_ready
        ) THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'SOURCE_REVISION_BUILD_REQUIRED';
        END IF;
    END IF;
    RETURN NULL;
END
$body$;
CREATE CONSTRAINT TRIGGER source_revision_family_guard AFTER INSERT OR UPDATE
ON public.ingestion_sourceconfigurationrevision DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION public.agenthub_source_revision_family_guard();

CREATE FUNCTION public.agenthub_source_revision_config_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
BEGIN
    IF EXISTS (SELECT 1 FROM public.ingestion_sourceconfigurationrevision r
               WHERE r.source_id = OLD.id)
       AND (TG_OP = 'DELETE' OR (to_jsonb(NEW) - ARRAY['status','updated_at']) IS DISTINCT FROM
                                  (to_jsonb(OLD) - ARRAY['status','updated_at'])) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'SOURCE_REVISION_CONFIG_IMMUTABLE';
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END
$body$;
CREATE TRIGGER source_revision_config_guard BEFORE UPDATE OR DELETE ON public.ingestion_source
FOR EACH ROW EXECUTE FUNCTION public.agenthub_source_revision_config_guard();
ALTER TABLE public.ingestion_sourceconfigurationrevision ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingestion_sourceconfigurationrevision FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.ingestion_sourceconfigurationrevision
USING (public.agenthub_tenant_scope_contains(organization_id))
WITH CHECK (public.agenthub_tenant_scope_contains(organization_id));
"""


def draft_guard(*, revised):
    sql = import_module("apps.ingestion.migrations.0030_rest_setup_draft").SQL
    sql = sql.split("CREATE TRIGGER rest_setup_draft_guard")[0]
    if revised:
        sql = sql.replace("'inputs','schedule'", "'inputs','schedule','base_source','base_token'")
        sql = sql.replace(
            "    RETURN NEW;",
            r"""
    IF NEW.payload ? 'base_source' OR NEW.payload ? 'base_token' THEN
        IF NOT (NEW.payload ? 'base_source' AND NEW.payload ? 'base_token')
           OR jsonb_typeof(NEW.payload->'base_source') <> 'number'
           OR (NEW.payload->>'base_source') !~ '^[1-9][0-9]{0,18}$'
           OR jsonb_typeof(NEW.payload->'base_token') <> 'string'
           OR (NEW.payload->>'base_token') !~ '^[0-9a-f]{64}$' THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'SOURCE_REVISION_DRAFT_INVALID';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM public.ingestion_source s
            WHERE s.id = (NEW.payload->>'base_source')::bigint
            AND s.organization_id = NEW.organization_id AND s.document_set_id = NEW.document_set_id
            AND s.connector_type = 'generic_rest') THEN
            RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'SOURCE_REVISION_DRAFT_SCOPE_INVALID';
        END IF;
    END IF;
    RETURN NEW;
""",
        )
    return sql.replace("CREATE FUNCTION", "CREATE OR REPLACE FUNCTION")


def install(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(SQL, params=None)
        schema_editor.execute(draft_guard(revised=True), params=None)


def reverse(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT rolsuper OR rolbypassrls FROM pg_roles WHERE rolname = current_user"
            )
            role = cursor.fetchone()
        if not role or not role[0]:
            raise RuntimeError("SOURCE_REVISION_ROLLBACK_REQUIRES_PRIVILEGED_ROLE")
    if (
        apps.get_model("ingestion", "SourceConfigurationRevision")
        .objects.using(schema_editor.connection.alias)
        .exists()
        or apps.get_model("ingestion", "RestSetupDraft")
        .objects.using(schema_editor.connection.alias)
        .filter(payload__has_key="base_source")
        .exists()
    ):
        raise RuntimeError("SOURCE_REVISION_ROLLBACK_REQUIRES_EMPTY_HISTORY")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("""
            DROP TRIGGER source_revision_config_guard ON public.ingestion_source;
            DROP FUNCTION public.agenthub_source_revision_config_guard();
            DROP TRIGGER source_revision_family_guard
                ON public.ingestion_sourceconfigurationrevision;
            DROP FUNCTION public.agenthub_source_revision_family_guard();
            DROP TRIGGER source_revision_guard ON public.ingestion_sourceconfigurationrevision;
            DROP FUNCTION public.agenthub_source_revision_guard();
        """)
        schema_editor.execute(draft_guard(revised=False), params=None)


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0032_resource_snapshot_schedule"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceConfigurationRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("base_token", models.CharField(blank=True, max_length=64)),
                ("schedule_config", models.JSONField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("created_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.organization",
                    ),
                ),
                (
                    "root_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="ingestion.source",
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuration_revision",
                        to="ingestion.source",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("root_source", "number"), name="source_revision_number"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("root_source",),
                        name="source_revision_current",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("number__gte", 1)),
                        name="source_revision_positive",
                    ),
                ],
            },
        ),
        migrations.RunPython(install, reverse),
    ]
