# Generated by Django 5.2.17 on 2026-09-11 08:11

import hashlib
import json
from importlib import import_module

import django.db.models.deletion
from django.db import migrations, models

# Frozen historical checksum contract: never import a changing runtime registry here.
MODEL_FIELDS = (
    "logical_id",
    "revision",
    "provider",
    "scheme",
    "host",
    "port",
    "path",
    "model",
    "secret_ref",
    "timeout_seconds",
    "max_response_bytes",
    "max_output_tokens",
)
EMBEDDING_FIELDS = (
    "logical_id",
    "revision",
    "provider",
    "scheme",
    "host",
    "port",
    "path",
    "model",
    "secret_ref",
    "dimensions",
    "index_type",
    "normalize",
    "distance_metric",
    "timeout_seconds",
    "max_response_bytes",
    "max_batch_size",
)
OCR_FIELDS = (
    "logical_id",
    "revision",
    "provider",
    "scheme",
    "host",
    "port",
    "base_path",
    "secret_ref",
    "timeout_seconds",
    "poll_interval_seconds",
    "max_poll_attempts",
    "max_upload_bytes",
    "max_pages",
    "max_result_bytes",
)
PROFILES = (
    ("orchestration", "ModelProfile", "model", MODEL_FIELDS),
    ("ingestion", "EmbeddingProfile", "embedding", EMBEDDING_FIELDS),
    ("ingestion", "OcrProfile", "ocr", OCR_FIELDS),
)


def original_identity_guard():
    sql = import_module("apps.ingestion.migrations.0027_mcp_resource_authority").SQL
    return sql.split("CREATE FUNCTION public.agenthub_mcp_resource_profile_guard")[0]


def install(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    branches = """
    ELSIF NEW.kind = 'model' THEN
        SELECT logical_id, revision INTO profile FROM public.orchestration_modelprofile
        WHERE id = NEW.model_profile_id FOR SHARE;
    ELSIF NEW.kind = 'embedding' THEN
        SELECT logical_id, revision INTO profile FROM public.ingestion_embeddingprofile
        WHERE id = NEW.embedding_profile_id FOR SHARE;
    ELSIF NEW.kind = 'ocr' THEN
        SELECT logical_id, revision INTO profile FROM public.ingestion_ocrprofile
        WHERE id = NEW.ocr_profile_id FOR SHARE;
"""
    sql = original_identity_guard().replace(
        "    ELSE\n        RAISE EXCEPTION", branches + "    ELSE\n        RAISE EXCEPTION", 1
    )
    schema_editor.execute(sql, params=None)
    schema_editor.execute(
        """
CREATE FUNCTION public.agenthub_model_connection_profile_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
BEGIN
    IF EXISTS (
        SELECT 1 FROM public.ingestion_connection c WHERE
        (TG_TABLE_NAME = 'orchestration_modelprofile' AND c.model_profile_id = OLD.id)
        OR (TG_TABLE_NAME = 'ingestion_embeddingprofile' AND c.embedding_profile_id = OLD.id)
        OR (TG_TABLE_NAME = 'ingestion_ocrprofile' AND c.ocr_profile_id = OLD.id)
    ) AND (TG_OP = 'DELETE' OR (to_jsonb(NEW) - 'status') IS DISTINCT FROM
                               (to_jsonb(OLD) - 'status')) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'CONNECTION_PROFILE_IMMUTABLE';
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END
$body$;
""",
        params=None,
    )
    for app, model, kind, _ in PROFILES:
        schema_editor.execute(
            f"""
CREATE TRIGGER connection_{kind}_profile_guard BEFORE UPDATE OR DELETE
ON public.{app}_{model.lower()} FOR EACH ROW
EXECUTE FUNCTION public.agenthub_model_connection_profile_guard();
""",
            params=None,
        )


def map_existing_profiles(apps, schema_editor):
    identity_model = apps.get_model("ingestion", "Connection")
    alias = schema_editor.connection.alias
    for app, model, kind, fields in PROFILES:
        profile_model = apps.get_model(app, model)
        for profile in profile_model.objects.using(alias).order_by("pk").iterator(chunk_size=200):
            body = {
                "contract": "connection-profile/v1",
                "kind": kind,
                "config": {field: getattr(profile, field) for field in fields},
            }
            checksum = hashlib.sha256(
                json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode(
                    "utf-8"
                )
            ).hexdigest()
            identity, _ = identity_model.objects.using(alias).get_or_create(
                **{f"{kind}_profile_id": profile.pk},
                defaults={
                    "kind": kind,
                    "logical_id": profile.logical_id,
                    "revision": profile.revision,
                    "profile_checksum": checksum,
                    "created_by": "typed-model-connection-migration",
                },
            )
            if (
                identity.kind,
                identity.logical_id,
                identity.revision,
                identity.profile_checksum,
            ) != (kind, profile.logical_id, profile.revision, checksum):
                raise RuntimeError("TYPED_CONNECTION_MAPPING_CONFLICT")


def reverse(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT rolsuper OR rolbypassrls FROM pg_roles WHERE rolname = current_user"
            )
            role = cursor.fetchone()
        if not role or not role[0]:
            raise RuntimeError("TYPED_CONNECTION_ROLLBACK_REQUIRES_PRIVILEGED_ROLE")
    if (
        apps.get_model("ingestion", "Connection")
        .objects.using(schema_editor.connection.alias)
        .filter(kind__in=["model", "embedding", "ocr"])
        .exists()
    ):
        raise RuntimeError("TYPED_CONNECTION_ROLLBACK_REQUIRES_EMPTY_HISTORY")
    if schema_editor.connection.vendor == "postgresql":
        for app, model, kind, _ in PROFILES:
            schema_editor.execute(
                f"DROP TRIGGER connection_{kind}_profile_guard ON public.{app}_{model.lower()}"
            )
        schema_editor.execute("DROP FUNCTION public.agenthub_model_connection_profile_guard()")
        schema_editor.execute(original_identity_guard(), params=None)


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0033_source_configuration_revision"),
        ("orchestration", "0001_modelprofile"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="connection",
            name="connection_profile_kind_consistent",
        ),
        migrations.AddField(
            model_name="connection",
            name="embedding_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connection_identity",
                to="ingestion.embeddingprofile",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="model_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connection_identity",
                to="orchestration.modelprofile",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="ocr_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connection_identity",
                to="ingestion.ocrprofile",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="kind",
            field=models.CharField(
                choices=[
                    ("rest_pull", "REST veri bağlantısı"),
                    ("confluence_dc", "Confluence veri bağlantısı"),
                    ("mcp_resource", "MCP belge bağlantısı"),
                    ("model", "Yanıt modeli bağlantısı"),
                    ("embedding", "Arama modeli bağlantısı"),
                    ("ocr", "Metin okuma bağlantısı"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("embedding_profile__isnull", True),
                        ("kind", "rest_pull"),
                        ("mcp_resource_profile__isnull", True),
                        ("model_profile__isnull", True),
                        ("ocr_profile__isnull", True),
                        ("rest_profile__isnull", False),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", False),
                        ("embedding_profile__isnull", True),
                        ("kind", "confluence_dc"),
                        ("mcp_resource_profile__isnull", True),
                        ("model_profile__isnull", True),
                        ("ocr_profile__isnull", True),
                        ("rest_profile__isnull", True),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("embedding_profile__isnull", True),
                        ("kind", "mcp_resource"),
                        ("mcp_resource_profile__isnull", False),
                        ("model_profile__isnull", True),
                        ("ocr_profile__isnull", True),
                        ("rest_profile__isnull", True),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("embedding_profile__isnull", True),
                        ("kind", "model"),
                        ("mcp_resource_profile__isnull", True),
                        ("model_profile__isnull", False),
                        ("ocr_profile__isnull", True),
                        ("rest_profile__isnull", True),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("embedding_profile__isnull", False),
                        ("kind", "embedding"),
                        ("mcp_resource_profile__isnull", True),
                        ("model_profile__isnull", True),
                        ("ocr_profile__isnull", True),
                        ("rest_profile__isnull", True),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("embedding_profile__isnull", True),
                        ("kind", "ocr"),
                        ("mcp_resource_profile__isnull", True),
                        ("model_profile__isnull", True),
                        ("ocr_profile__isnull", False),
                        ("rest_profile__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="connection_profile_kind_consistent",
            ),
        ),
        migrations.RunPython(install, reverse),
        migrations.RunPython(map_existing_profiles, migrations.RunPython.noop),
    ]
