# Generated by Django 5.2.17 on 2026-09-11 09:01

import hashlib
import json
from importlib import import_module

import django.db.models.deletion
from django.db import migrations, models


def previous_identity_guard():
    previous = import_module("apps.ingestion.migrations.0034_typed_model_connections")
    branches = """
    ELSIF NEW.kind = 'model' THEN
        SELECT logical_id, revision INTO profile FROM public.orchestration_modelprofile
        WHERE id = NEW.model_profile_id FOR SHARE;
    ELSIF NEW.kind = 'embedding' THEN
        SELECT logical_id, revision INTO profile FROM public.ingestion_embeddingprofile
        WHERE id = NEW.embedding_profile_id FOR SHARE;
    ELSIF NEW.kind = 'ocr' THEN
        SELECT logical_id, revision INTO profile FROM public.ingestion_ocrprofile
        WHERE id = NEW.ocr_profile_id FOR SHARE;
"""
    return previous.original_identity_guard().replace(
        "    ELSE\n        RAISE EXCEPTION", branches + "    ELSE\n        RAISE EXCEPTION", 1
    )


def require_privileged_role(schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT rolsuper OR rolbypassrls FROM pg_roles WHERE rolname = current_user"
            )
            role = cursor.fetchone()
        if not role or not role[0]:
            raise RuntimeError("TOOL_CONNECTION_MIGRATION_REQUIRES_PRIVILEGED_ROLE")


def install(apps, schema_editor):
    require_privileged_role(schema_editor)
    if schema_editor.connection.vendor != "postgresql":
        return
    sql = previous_identity_guard().replace(
        "SELECT logical_id, revision INTO profile",
        "SELECT logical_id, revision, NULL::bigint AS organization_id INTO profile",
    ).replace(
        "    ELSE\n        RAISE EXCEPTION",
        """    ELSIF NEW.kind = 'tool' THEN
        SELECT logical_id, version AS revision, organization_id INTO profile
        FROM public.tools_tooldefinition WHERE id = NEW.tool_definition_id;
    ELSE
        RAISE EXCEPTION""",
        1,
    ).replace(
        "    IF NOT FOUND OR NEW.logical_id IS DISTINCT FROM profile.logical_id",
        """    IF NOT FOUND OR NEW.organization_id IS DISTINCT FROM profile.organization_id
       OR NEW.logical_id IS DISTINCT FROM profile.logical_id""",
    )
    schema_editor.execute(sql, params=None)
    schema_editor.execute("""
CREATE FUNCTION public.agenthub_tool_connection_profile_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
BEGIN
    IF TG_OP = 'DELETE' OR (to_jsonb(NEW) - ARRAY['status', 'updated_at']) IS DISTINCT FROM
                          (to_jsonb(OLD) - ARRAY['status', 'updated_at']) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'CONNECTION_PROFILE_IMMUTABLE';
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END
$body$;
CREATE TRIGGER connection_tool_profile_guard BEFORE UPDATE OR DELETE
ON public.tools_tooldefinition FOR EACH ROW
EXECUTE FUNCTION public.agenthub_tool_connection_profile_guard();

ALTER TABLE public.ingestion_connection ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingestion_connection FORCE ROW LEVEL SECURITY;
CREATE POLICY connection_read_scope ON public.ingestion_connection FOR SELECT
USING (organization_id IS NULL OR public.agenthub_tenant_scope_contains(organization_id));
CREATE POLICY connection_tool_insert_scope ON public.ingestion_connection FOR INSERT
WITH CHECK (kind = 'tool' AND organization_id IS NOT NULL
            AND public.agenthub_tenant_scope_contains(organization_id));
""", params=None)


def checksum(body):
    return hashlib.sha256(
        json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    ).hexdigest()


def map_existing_tools(apps, schema_editor):
    # Frozen historical contract. No changing runtime services or credential resolution.
    require_privileged_role(schema_editor)
    alias = schema_editor.connection.alias
    identity_model = apps.get_model("ingestion", "Connection")
    profile_model = apps.get_model("tools", "ToolDefinition")
    profiles = profile_model.objects.using(alias).select_related("organization").order_by("pk")
    for profile in profiles.iterator(chunk_size=200):
        manifest = profile.manifest
        spec = manifest.get("spec", {}) if isinstance(manifest, dict) else {}
        if (
            not isinstance(spec, dict)
            or checksum(manifest) != profile.checksum
            or profile.protocol != spec.get("protocol")
            or profile.risk != spec.get("risk")
            or profile.side_effecting != spec.get("side_effecting")
            or not isinstance(spec.get("allowed_organizations"), list)
            or profile.organization.slug not in spec["allowed_organizations"]
            or profile.version < 1
        ):
            raise RuntimeError("TOOL_CONNECTION_HISTORICAL_PROFILE_INVALID")
        expected = checksum({
            "contract": "connection-profile/v1",
            "kind": "tool",
            "config": {
                "organization_id": profile.organization_id,
                "logical_id": profile.logical_id,
                "revision": profile.version,
                "manifest_checksum": profile.checksum,
            },
        })
        identity, _ = identity_model.objects.using(alias).get_or_create(
            tool_definition_id=profile.pk,
            defaults={
                "organization_id": profile.organization_id,
                "kind": "tool",
                "logical_id": profile.logical_id,
                "revision": profile.version,
                "profile_checksum": expected,
                "created_by": "tool-connection-migration",
            },
        )
        if (
            identity.organization_id, identity.kind, identity.logical_id,
            identity.revision, identity.profile_checksum,
        ) != (profile.organization_id, "tool", profile.logical_id, profile.version, expected):
            raise RuntimeError("TOOL_CONNECTION_MAPPING_CONFLICT")
    if schema_editor.connection.vendor == "postgresql":
        # Django creates the new FK's index through deferred schema SQL after
        # RunPython. Drain the backfill's deferred FK checks before that DDL;
        # constraints remain enforced and the migration remains atomic.
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SET CONSTRAINTS ALL IMMEDIATE")
            cursor.execute("SET CONSTRAINTS ALL DEFERRED")


def reverse(apps, schema_editor):
    require_privileged_role(schema_editor)
    if apps.get_model("ingestion", "Connection").objects.using(
        schema_editor.connection.alias
    ).filter(kind="tool").exists():
        raise RuntimeError("TOOL_CONNECTION_ROLLBACK_REQUIRES_EMPTY_HISTORY")
    if schema_editor.connection.vendor == "postgresql":
        # Removing the tenant INSERT policy must not leave the new app grant able
        # to write global identities on the pre-0035 schema.
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                WITH relation AS (
                    SELECT oid, relowner, relacl FROM pg_class
                    WHERE oid = 'public.ingestion_connection'::regclass
                ), grants AS (
                    SELECT r.relowner, a.grantee, a.privilege_type FROM relation r,
                    LATERAL aclexplode(COALESCE(r.relacl, acldefault('r', r.relowner))) a
                    UNION ALL
                    SELECT r.relowner, a.grantee, a.privilege_type FROM relation r
                    JOIN pg_attribute col ON col.attrelid = r.oid,
                    LATERAL aclexplode(col.attacl) a
                )
                SELECT EXISTS (SELECT 1 FROM grants g LEFT JOIN pg_roles r ON r.oid = g.grantee
                WHERE g.privilege_type = 'INSERT' AND g.grantee <> g.relowner
                AND (g.grantee = 0 OR NOT (r.rolsuper OR r.rolbypassrls)))
            """)
            if cursor.fetchone()[0]:
                raise RuntimeError("TOOL_CONNECTION_ROLLBACK_REQUIRES_INSERT_REVOCATION")
        schema_editor.execute("""
DROP POLICY connection_tool_insert_scope ON public.ingestion_connection;
DROP POLICY connection_read_scope ON public.ingestion_connection;
ALTER TABLE public.ingestion_connection NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.ingestion_connection DISABLE ROW LEVEL SECURITY;
DROP TRIGGER connection_tool_profile_guard ON public.tools_tooldefinition;
DROP FUNCTION public.agenthub_tool_connection_profile_guard();
""", params=None)
        schema_editor.execute(previous_identity_guard(), params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0034_typed_model_connections"),
        ("orchestration", "0001_modelprofile"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
        ("tools", "0006_typed_approval_actors"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="connection",
            name="uniq_connection_kind_revision",
        ),
        migrations.RemoveConstraint(
            model_name="connection",
            name="connection_profile_kind_consistent",
        ),
        migrations.AddField(
            model_name="connection",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="tenancy.organization",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="tool_definition",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connection_identity",
                to="tools.tooldefinition",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="kind",
            field=models.CharField(
                choices=[
                    ("rest_pull", "REST veri bağlantısı"),
                    ("confluence_dc", "Confluence veri bağlantısı"),
                    ("mcp_resource", "MCP belge bağlantısı"),
                    ("model", "Yanıt modeli bağlantısı"),
                    ("embedding", "Arama modeli bağlantısı"),
                    ("ocr", "Metin okuma bağlantısı"),
                    ("tool", "Araç bağlantısı"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", True)),
                fields=("kind", "logical_id", "revision"),
                name="uniq_connection_kind_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("organization", "kind", "logical_id", "revision"),
                name="uniq_connection_org_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("embedding_profile__isnull", True),
                        ("kind", "rest_pull"),
                        ("mcp_resource_profile__isnull", True),
                        ("model_profile__isnull", True),
                        ("ocr_profile__isnull", True),
                        ("organization__isnull", True),
                        ("rest_profile__isnull", False),
                        ("tool_definition__isnull", True),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", False),
                        ("embedding_profile__isnull", True),
                        ("kind", "confluence_dc"),
                        ("mcp_resource_profile__isnull", True),
                        ("model_profile__isnull", True),
                        ("ocr_profile__isnull", True),
                        ("organization__isnull", True),
                        ("rest_profile__isnull", True),
                        ("tool_definition__isnull", True),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("embedding_profile__isnull", True),
                        ("kind", "mcp_resource"),
                        ("mcp_resource_profile__isnull", False),
                        ("model_profile__isnull", True),
                        ("ocr_profile__isnull", True),
                        ("organization__isnull", True),
                        ("rest_profile__isnull", True),
                        ("tool_definition__isnull", True),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("embedding_profile__isnull", True),
                        ("kind", "model"),
                        ("mcp_resource_profile__isnull", True),
                        ("model_profile__isnull", False),
                        ("ocr_profile__isnull", True),
                        ("organization__isnull", True),
                        ("rest_profile__isnull", True),
                        ("tool_definition__isnull", True),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("embedding_profile__isnull", False),
                        ("kind", "embedding"),
                        ("mcp_resource_profile__isnull", True),
                        ("model_profile__isnull", True),
                        ("ocr_profile__isnull", True),
                        ("organization__isnull", True),
                        ("rest_profile__isnull", True),
                        ("tool_definition__isnull", True),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("embedding_profile__isnull", True),
                        ("kind", "ocr"),
                        ("mcp_resource_profile__isnull", True),
                        ("model_profile__isnull", True),
                        ("ocr_profile__isnull", False),
                        ("organization__isnull", True),
                        ("rest_profile__isnull", True),
                        ("tool_definition__isnull", True),
                    ),
                    models.Q(
                        ("confluence_profile__isnull", True),
                        ("embedding_profile__isnull", True),
                        ("kind", "tool"),
                        ("mcp_resource_profile__isnull", True),
                        ("model_profile__isnull", True),
                        ("ocr_profile__isnull", True),
                        ("organization__isnull", False),
                        ("rest_profile__isnull", True),
                        ("tool_definition__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="connection_profile_kind_consistent",
            ),
        ),
        migrations.RunPython(install, reverse),
        migrations.RunPython(map_existing_tools, migrations.RunPython.noop),
    ]
