# Generated by Django 5.2.17 on 2026-09-11 09:20

from django.conf import settings
from importlib import import_module

from django.db import migrations, models


def previous_guard():
    return import_module(
        "apps.ingestion.migrations.0033_source_configuration_revision"
    ).draft_guard(revised=True)


def install(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    sql = previous_guard().replace("BEGIN\n", """BEGIN
    IF TG_OP = 'INSERT' AND NEW.payload_purged_at IS NOT NULL THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'REST_SETUP_DRAFT_PURGE_INVALID';
    END IF;
    IF TG_OP = 'UPDATE' THEN
        IF OLD.payload_purged_at IS NOT NULL THEN
            RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'REST_SETUP_DRAFT_BINDING_IMMUTABLE';
        END IF;
        IF NEW.payload_purged_at IS NOT NULL THEN
            IF NEW.payload_purged_at < OLD.expires_at
               OR NEW.payload_purged_at > statement_timestamp()
               OR NEW.payload <> '{}'::jsonb OR NEW.name <> ''
               OR NEW.completed_source_id IS NOT NULL THEN
                RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'REST_SETUP_DRAFT_PURGE_INVALID';
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_class WHERE oid = TG_RELID
                           AND pg_get_userbyid(relowner) = current_user) THEN
                RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'REST_SETUP_RETENTION_OWNER_REQUIRED';
            END IF;
        END IF;
    END IF;
""", 1)
    schema_editor.execute(sql, params=None)


def reverse(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT rolsuper OR rolbypassrls FROM pg_roles WHERE rolname = current_user")
            if not cursor.fetchone()[0]:
                raise RuntimeError("REST_SETUP_RETENTION_ROLLBACK_REQUIRES_PRIVILEGED_ROLE")
    if apps.get_model("ingestion", "RestSetupDraft").objects.using(
        schema_editor.connection.alias
    ).filter(payload_purged_at__isnull=False).exists():
        raise RuntimeError("REST_SETUP_RETENTION_ROLLBACK_REQUIRES_EMPTY_HISTORY")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(previous_guard(), params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_explicit_shared_data_access"),
        ("ingestion", "0035_tenant_tool_connections"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restsetupdraft",
            name="payload_purged_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name="restsetupdraft",
            index=models.Index(
                condition=models.Q(
                    ("completed_source__isnull", True),
                    ("payload_purged_at__isnull", True),
                ),
                fields=["organization", "expires_at", "id"],
                name="rest_draft_retention_queue",
            ),
        ),
        migrations.AddConstraint(
            model_name="restsetupdraft",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("payload_purged_at__isnull", True),
                    models.Q(
                        ("completed_source__isnull", True),
                        ("name", ""),
                        ("payload", {}),
                        ("payload_purged_at__gte", models.F("expires_at")),
                    ),
                    _connector="OR",
                ),
                name="rest_draft_purged_payload_empty",
            ),
        ),
        migrations.RunPython(install, reverse),
    ]
