# Generated by Django 5.2.16 on 2026-07-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('canary', 'Canary'), ('active', 'Active'), ('superseded', 'Superseded'), ('rolled_back', 'Rolled back')], default='candidate', max_length=16)),
                ('runtime_version', models.CharField(max_length=64)),
                ('manifest', models.JSONField()),
                ('artifact_manifest_sha256', models.CharField(max_length=64)),
                ('created_by', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='catalog.scenario')),
            ],
            options={
                'ordering': ['scenario_id', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('scenario',), name='uniq_active_release_per_scenario')],
            },
        ),
    ]
