# Generated by Django 5.2.16 on 2026-07-10 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('identity', '0002_consumertoken'),
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseCanary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped'), ('expired', 'Expired')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canaries', to='identity.consumer')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canaries', to='releases.scenariorelease')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canaries', to='catalog.scenario')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('scenario', 'consumer'), name='uniq_active_canary_per_consumer_scenario')],
            },
        ),
    ]
