# Generated by Django 5.2.17 on 2026-09-10 04:00

import django.db.models.deletion
from django.db import migrations, models


def protect_revision(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        ALTER TABLE public.releases_scenariorevision ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.releases_scenariorevision FORCE ROW LEVEL SECURITY;
        CREATE POLICY tenant_isolation ON public.releases_scenariorevision
        USING (agenthub_tenant_scope_contains(organization_id))
        WITH CHECK (agenthub_tenant_scope_contains(organization_id));

        CREATE FUNCTION public.agenthub_revision_integrity() RETURNS trigger
        LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
        DECLARE pin jsonb;
        BEGIN
          IF TG_OP <> 'INSERT' THEN
            RAISE EXCEPTION 'SCENARIO_REVISION_IMMUTABLE' USING ERRCODE = '23514';
          END IF;
          -- Serialize capture against a concurrent legacy workflow writer. The
          -- companion immutable-workflow trigger fences subsequent updates.
          PERFORM 1 FROM public.workflows_workflowversion
          WHERE id = NEW.workflow_version_id FOR SHARE;
          IF NEW.contract_version <> 'scenario-revision/v1'
             OR NEW.snapshot->>'contract' IS DISTINCT FROM NEW.contract_version
             OR NEW.snapshot->'scope' IS DISTINCT FROM jsonb_build_object(
                'organization_id', NEW.organization_id, 'scenario_id', NEW.scenario_id,
                'source_release_id', NEW.source_release_id)
             OR (NEW.snapshot->'workflow'->>'id')::bigint IS DISTINCT FROM NEW.workflow_version_id
             OR octet_length(NEW.snapshot::text) > 4194304
             OR NOT EXISTS (
                SELECT 1 FROM public.releases_scenariorelease r
                JOIN public.catalog_scenario s ON s.id = r.scenario_id
                JOIN public.catalog_aiproject p ON p.id = s.project_id
                JOIN public.workflows_workflowversion w ON w.id = NEW.workflow_version_id
                WHERE r.id = NEW.source_release_id AND r.scenario_id = NEW.scenario_id
                  AND r.organization_id = NEW.organization_id AND s.organization_id = NEW.organization_id
                  AND p.organization_id = NEW.organization_id AND w.organization_id = NEW.organization_id
                  AND w.scenario_id = NEW.scenario_id AND r.manifest = NEW.snapshot->'manifest'
                  AND r.artifact_manifest_sha256 = NEW.source_manifest_checksum
                  AND w.compiled_graph = NEW.snapshot->'workflow'->'graph'
                  AND w.checksum = NEW.snapshot->'workflow'->>'checksum'
                  AND w.compiler_version = NEW.snapshot->'workflow'->>'compiler_version'
                  AND w.source_artifact_id = (NEW.snapshot->'artifacts'->'workflow_definition'->>'id')::bigint
             ) THEN
            RAISE EXCEPTION 'SCENARIO_REVISION_SCOPE_INVALID' USING ERRCODE = '23514';
          END IF;
          IF (
              SELECT count(*) FROM public.documents_documentset d
              WHERE d.organization_id = NEW.organization_id AND d.id IN (
                SELECT value::bigint FROM jsonb_array_elements_text(
                  NEW.snapshot->'data'->'document_set_ids'))
          ) <> jsonb_array_length(NEW.snapshot->'data'->'document_set_ids')
          OR (
              SELECT count(*) FROM public.documents_documentsetversion v
              WHERE v.organization_id = NEW.organization_id AND v.id IN (
                SELECT value::bigint FROM jsonb_array_elements_text(
                  NEW.snapshot->'data'->'document_set_version_ids'))
          ) <> jsonb_array_length(NEW.snapshot->'data'->'document_set_version_ids')
          OR (
              SELECT count(*) FROM public.ingestion_indexversion i
              WHERE i.organization_id = NEW.organization_id AND i.id IN (
                SELECT value::bigint FROM jsonb_array_elements_text(
                  NEW.snapshot->'data'->'index_version_ids'))
          ) <> jsonb_array_length(NEW.snapshot->'data'->'index_version_ids') THEN
            RAISE EXCEPTION 'SCENARIO_REVISION_DATA_SCOPE_INVALID' USING ERRCODE = '23514';
          END IF;
          FOR pin IN SELECT value FROM jsonb_each(NEW.snapshot->'artifacts') LOOP
            IF NOT EXISTS (
                SELECT 1 FROM public.artifacts_artifactversion a
                WHERE a.id = (pin->>'id')::bigint AND a.organization_id = NEW.organization_id
                  AND a.type = pin->>'type' AND a.body = pin->'body' AND a.checksum = pin->>'checksum'
                  AND a.logical_id || ':v' || a.version::text = pin->>'ref'
            ) THEN
              RAISE EXCEPTION 'SCENARIO_REVISION_ARTIFACT_INVALID' USING ERRCODE = '23514';
            END IF;
          END LOOP;
          RETURN NEW;
        END $$;
        CREATE TRIGGER scenario_revision_integrity BEFORE INSERT OR UPDATE OR DELETE
        ON public.releases_scenariorevision FOR EACH ROW
        EXECUTE FUNCTION public.agenthub_revision_integrity();
    """)


def unprotect_revision(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        DROP TRIGGER scenario_revision_integrity ON public.releases_scenariorevision;
        DROP FUNCTION public.agenthub_revision_integrity();
        DROP POLICY tenant_isolation ON public.releases_scenariorevision;
        ALTER TABLE public.releases_scenariorevision NO FORCE ROW LEVEL SECURITY;
        ALTER TABLE public.releases_scenariorevision DISABLE ROW LEVEL SECURITY;
    """)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_explicit_shared_data_access"),
        ("documents", "0011_explicit_shared_data_access"),
        ("ingestion", "0020_shared_build_attempt_integrity"),
        ("releases", "0003_direct_tenant_lineage"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
        ("workflows", "0018_remove_runwait_allowed_roles_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveBigIntegerField()),
                ("contract_version", models.CharField(max_length=32)),
                ("snapshot", models.JSONField()),
                ("checksum", models.CharField(max_length=64)),
                ("source_manifest_checksum", models.CharField(max_length=64)),
                ("created_by", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.organization",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="catalog.scenario",
                    ),
                ),
                (
                    "source_release",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_revision",
                        to="releases.scenariorelease",
                    ),
                ),
                (
                    "workflow_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workflows.workflowversion",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario_id", "-number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scenario", "number"),
                        name="uniq_scenario_revision_number",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("number__gt", 0)),
                        name="scenario_revision_number_positive",
                    ),
                ],
            },
        ),
        migrations.RunPython(protect_revision, unprotect_revision),
    ]
