# Generated by Django 5.2.17 on 2026-09-10 04:27

from django.db import migrations, models


def protect_execution_contract(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
      CREATE FUNCTION public.agenthub_release_execution_pins() RETURNS trigger
      LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
      BEGIN
        IF NEW.execution_contract IS DISTINCT FROM OLD.execution_contract OR (
          OLD.execution_contract = 'scenario-revision/v1' AND (
            NEW.organization_id, NEW.scenario_id, NEW.manifest,
            NEW.artifact_manifest_sha256, NEW.runtime_version
          ) IS DISTINCT FROM (
            OLD.organization_id, OLD.scenario_id, OLD.manifest,
            OLD.artifact_manifest_sha256, OLD.runtime_version
          )
        ) THEN
          RAISE EXCEPTION 'RELEASE_EXECUTION_PINS_IMMUTABLE' USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER release_execution_pins BEFORE UPDATE
      ON public.releases_scenariorelease FOR EACH ROW
      EXECUTE FUNCTION public.agenthub_release_execution_pins();

      CREATE FUNCTION public.agenthub_release_revision_required() RETURNS trigger
      LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
      BEGIN
        IF NEW.execution_contract = 'scenario-revision/v1' AND NOT EXISTS (
          SELECT 1 FROM public.releases_scenariorevision v
          WHERE v.source_release_id = NEW.id AND v.organization_id = NEW.organization_id
            AND v.scenario_id = NEW.scenario_id
        ) THEN
          RAISE EXCEPTION 'RELEASE_REVISION_REQUIRED' USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
      END $$;
      CREATE CONSTRAINT TRIGGER release_revision_required AFTER INSERT
      ON public.releases_scenariorelease DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW EXECUTE FUNCTION public.agenthub_release_revision_required();

      CREATE FUNCTION public.agenthub_revision_workflow_immutable() RETURNS trigger
      LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
      BEGIN
        IF EXISTS (SELECT 1 FROM public.releases_scenariorevision WHERE workflow_version_id = OLD.id)
        THEN
          RAISE EXCEPTION 'REVISION_WORKFLOW_IMMUTABLE' USING ERRCODE = '23514';
        END IF;
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER revision_workflow_immutable BEFORE UPDATE OR DELETE
      ON public.workflows_workflowversion FOR EACH ROW
      EXECUTE FUNCTION public.agenthub_revision_workflow_immutable();
    """)


def unprotect_execution_contract(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
      DROP TRIGGER revision_workflow_immutable ON public.workflows_workflowversion;
      DROP FUNCTION public.agenthub_revision_workflow_immutable();
      DROP TRIGGER release_revision_required ON public.releases_scenariorelease;
      DROP FUNCTION public.agenthub_release_revision_required();
      DROP TRIGGER release_execution_pins ON public.releases_scenariorelease;
      DROP FUNCTION public.agenthub_release_execution_pins();
    """)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_execution_revision_binding"),
        ("releases", "0004_scenario_revision_foundation"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariorelease",
            name="execution_contract",
            field=models.CharField(
                choices=[
                    ("legacy", "Mevcut sürüm çözümleme"),
                    ("scenario-revision/v1", "Tek senaryo sürümü"),
                ],
                db_default="legacy",
                default="legacy",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariorelease",
            constraint=models.CheckConstraint(
                condition=models.Q(("execution_contract__in", ["legacy", "scenario-revision/v1"])),
                name="release_execution_contract_valid",
            ),
        ),
        migrations.RunPython(protect_execution_contract, unprotect_execution_contract),
    ]
