# Generated by Django 5.2.17 on 2026-09-11 08:24

import uuid

import django.db.models.deletion
from django.db import migrations, models

SQL = r"""
CREATE FUNCTION public.agenthub_publication_intent_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
BEGIN
    IF TG_OP = 'DELETE' OR (TG_OP = 'UPDATE' AND (
       (to_jsonb(NEW) - 'completed_at') IS DISTINCT FROM (to_jsonb(OLD) - 'completed_at')
       OR (OLD.completed_at IS NOT NULL AND NEW.completed_at IS DISTINCT FROM OLD.completed_at)
    )) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'PUBLICATION_INTENT_IMMUTABLE';
    END IF;
    IF NEW.request_checksum !~ '^[0-9a-f]{64}$' OR NEW.prepared_checksum !~ '^[0-9a-f]{64}$'
       OR NOT EXISTS (
        SELECT 1 FROM public.catalog_scenario s
        JOIN public.builder_workflowdraft d ON d.scenario_id = s.id
        JOIN public.releases_scenariorelease r ON r.scenario_id = s.id
        JOIN public.evaluations_evalrun e ON e.release_id = r.id
        WHERE s.id = NEW.scenario_id AND s.organization_id = NEW.organization_id
          AND d.id = NEW.draft_id AND d.organization_id = NEW.organization_id
          AND d.project_id = s.project_id
          AND r.id = NEW.release_id AND r.organization_id = NEW.organization_id
          AND e.id = NEW.evaluation_id AND e.organization_id = NEW.organization_id
          AND (NEW.baseline_release_id IS NULL OR EXISTS (
              SELECT 1 FROM public.releases_scenariorelease b
              WHERE b.id = NEW.baseline_release_id AND b.organization_id = NEW.organization_id
                AND b.scenario_id = NEW.scenario_id
          ))
       ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PUBLICATION_SCOPE_INVALID';
    END IF;
    IF NEW.completed_at IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.releases_scenariorelease r
        JOIN public.catalog_scenario s ON s.id = r.scenario_id
        JOIN public.evaluations_evalrun e ON e.release_id = r.id
        WHERE r.id = NEW.release_id AND e.id = NEW.evaluation_id AND r.status = 'active'
          AND s.status = 'active' AND e.status = 'passed'
          AND e.total_cases > 0 AND e.passed_cases = e.total_cases
          AND e.total_cases = (SELECT count(*) FROM public.evaluations_evalcaseresult c
                               WHERE c.run_id = e.id AND c.passed)
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PUBLICATION_COMPLETION_INVALID';
    END IF;
    RETURN NEW;
END
$body$;
CREATE TRIGGER publication_intent_guard BEFORE INSERT OR UPDATE OR DELETE
ON public.releases_scenariopublication FOR EACH ROW
EXECUTE FUNCTION public.agenthub_publication_intent_guard();

CREATE FUNCTION public.agenthub_publication_pins_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
BEGIN
    IF TG_TABLE_NAME = 'releases_scenariorelease' AND EXISTS (
        SELECT 1 FROM public.releases_scenariopublication p WHERE p.release_id = OLD.id
    ) AND (TG_OP = 'DELETE' OR
       (to_jsonb(NEW) - ARRAY['status','promoted_at']) IS DISTINCT FROM
       (to_jsonb(OLD) - ARRAY['status','promoted_at'])) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'PUBLICATION_RELEASE_IMMUTABLE';
    END IF;
    IF TG_TABLE_NAME = 'evaluations_evalrun' AND EXISTS (
        SELECT 1 FROM public.releases_scenariopublication p WHERE p.evaluation_id = OLD.id
    ) AND (TG_OP = 'DELETE' OR
       (to_jsonb(NEW) - ARRAY['status','passed_cases','error_code','finished_at','updated_at'])
          IS DISTINCT FROM
       (to_jsonb(OLD) - ARRAY[
           'status','passed_cases','error_code','finished_at','updated_at'])) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'PUBLICATION_EVALUATION_IMMUTABLE';
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END
$body$;
CREATE TRIGGER publication_release_pins BEFORE UPDATE OR DELETE
ON public.releases_scenariorelease FOR EACH ROW
EXECUTE FUNCTION public.agenthub_publication_pins_guard();
CREATE TRIGGER publication_evaluation_pins BEFORE UPDATE OR DELETE
ON public.evaluations_evalrun FOR EACH ROW
EXECUTE FUNCTION public.agenthub_publication_pins_guard();

CREATE FUNCTION public.agenthub_publication_case_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
BEGIN
    IF EXISTS (SELECT 1 FROM public.releases_scenariopublication p
               WHERE p.evaluation_id = OLD.run_id) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'PUBLICATION_CASE_IMMUTABLE';
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END
$body$;
CREATE TRIGGER publication_case_guard BEFORE UPDATE OR DELETE
ON public.evaluations_evalcaseresult FOR EACH ROW
EXECUTE FUNCTION public.agenthub_publication_case_guard();

ALTER TABLE public.releases_scenariopublication ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.releases_scenariopublication FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON public.releases_scenariopublication
USING (public.agenthub_tenant_scope_contains(organization_id))
WITH CHECK (public.agenthub_tenant_scope_contains(organization_id));
"""


def install(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(SQL, params=None)


def reverse(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT rolsuper OR rolbypassrls FROM pg_roles WHERE rolname = current_user"
            )
            role = cursor.fetchone()
        if not role or not role[0]:
            raise RuntimeError("PUBLICATION_ROLLBACK_REQUIRES_PRIVILEGED_ROLE")
    if (
        apps.get_model("releases", "ScenarioPublication")
        .objects.using(schema_editor.connection.alias)
        .exists()
    ):
        raise RuntimeError("PUBLICATION_ROLLBACK_REQUIRES_EMPTY_HISTORY")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("""
            DROP TRIGGER publication_case_guard ON public.evaluations_evalcaseresult;
            DROP FUNCTION public.agenthub_publication_case_guard();
            DROP TRIGGER publication_release_pins ON public.releases_scenariorelease;
            DROP TRIGGER publication_evaluation_pins ON public.evaluations_evalrun;
            DROP FUNCTION public.agenthub_publication_pins_guard();
            DROP TRIGGER publication_intent_guard ON public.releases_scenariopublication;
            DROP FUNCTION public.agenthub_publication_intent_guard();
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0008_artifactdraft_model_profile"),
        ("catalog", "0013_durable_retrieval_selection"),
        ("evaluations", "0005_questioncase_expected_answer"),
        ("releases", "0005_execution_revision_binding"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("request_checksum", models.CharField(max_length=64)),
                ("prepared_checksum", models.CharField(max_length=64)),
                ("created_by", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "baseline_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="releases.scenariorelease",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="builder.workflowdraft",
                    ),
                ),
                (
                    "evaluation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="evaluations.evalrun",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.organization",
                    ),
                ),
                (
                    "release",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication",
                        to="releases.scenariorelease",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publications",
                        to="catalog.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.RunPython(install, reverse),
    ]
