# Generated by Django 5.2.17 on 2026-09-11 10:14

import django.db.models.deletion
from django.db import migrations, models


BEFORE = r"""
CREATE OR REPLACE FUNCTION public.agenthub_publication_intent_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
BEGIN
    IF TG_OP = 'DELETE' OR (TG_OP = 'UPDATE' AND (
       (to_jsonb(NEW) - 'completed_at') IS DISTINCT FROM (to_jsonb(OLD) - 'completed_at')
       OR (OLD.completed_at IS NOT NULL AND NEW.completed_at IS DISTINCT FROM OLD.completed_at)
    )) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'PUBLICATION_INTENT_IMMUTABLE';
    END IF;
    IF NEW.request_checksum !~ '^[0-9a-f]{64}$' OR NEW.prepared_checksum !~ '^[0-9a-f]{64}$'
       OR NOT EXISTS (
        SELECT 1 FROM public.catalog_scenario s
        JOIN public.builder_workflowdraft d ON d.scenario_id = s.id
        JOIN public.releases_scenariorelease r ON r.scenario_id = s.id
        JOIN public.evaluations_evalrun e ON e.release_id = r.id
        WHERE s.id = NEW.scenario_id AND s.organization_id = NEW.organization_id
          AND d.id = NEW.draft_id AND d.organization_id = NEW.organization_id
          AND d.project_id = s.project_id
          AND r.id = NEW.release_id AND r.organization_id = NEW.organization_id
          AND e.id = NEW.evaluation_id AND e.organization_id = NEW.organization_id
          AND (NEW.baseline_release_id IS NULL OR EXISTS (
              SELECT 1 FROM public.releases_scenariorelease b
              WHERE b.id = NEW.baseline_release_id AND b.organization_id = NEW.organization_id
                AND b.scenario_id = NEW.scenario_id
          ))
       ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PUBLICATION_SCOPE_INVALID';
    END IF;
    IF NEW.completed_at IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.releases_scenariorelease r
        JOIN public.catalog_scenario s ON s.id = r.scenario_id
        JOIN public.evaluations_evalrun e ON e.release_id = r.id
        WHERE r.id = NEW.release_id AND e.id = NEW.evaluation_id AND r.status = 'active'
          AND s.status = 'active' AND e.status = 'passed'
          AND e.total_cases > 0 AND e.passed_cases = e.total_cases
          AND e.total_cases = (SELECT count(*) FROM public.evaluations_evalcaseresult c
                               WHERE c.run_id = e.id AND c.passed)
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PUBLICATION_COMPLETION_INVALID';
    END IF;
    RETURN NEW;
END
$body$;
"""

AFTER = r"""
CREATE OR REPLACE FUNCTION public.agenthub_publication_intent_guard() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog AS $body$
BEGIN
    IF TG_OP = 'DELETE' OR (TG_OP = 'UPDATE' AND (
       (to_jsonb(NEW) - 'completed_at') IS DISTINCT FROM (to_jsonb(OLD) - 'completed_at')
       OR (OLD.completed_at IS NOT NULL AND NEW.completed_at IS DISTINCT FROM OLD.completed_at)
    )) THEN
        RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'PUBLICATION_INTENT_IMMUTABLE';
    END IF;
    IF NEW.request_checksum !~ '^[0-9a-f]{64}$' OR NEW.prepared_checksum !~ '^[0-9a-f]{64}$'
       OR NOT EXISTS (
        SELECT 1 FROM public.catalog_scenario s
        LEFT JOIN public.builder_workflowdraft d ON d.id = NEW.draft_id AND d.scenario_id = s.id
        JOIN public.releases_scenariorelease r ON r.scenario_id = s.id
        JOIN public.evaluations_evalrun e ON e.release_id = r.id
        WHERE s.id = NEW.scenario_id AND s.organization_id = NEW.organization_id
          AND (
            (NEW.source_job_id IS NULL AND d.id = NEW.draft_id
             AND d.organization_id = NEW.organization_id AND d.project_id = s.project_id)
            OR (NEW.draft_id IS NULL AND NEW.source_job_id IS NOT NULL
                AND NEW.source_job_id = e.prepared_source_job_id
                AND NEW.baseline_release_id IS NOT NULL)
          )
          AND r.id = NEW.release_id AND r.organization_id = NEW.organization_id
          AND e.id = NEW.evaluation_id AND e.organization_id = NEW.organization_id
          AND (NEW.baseline_release_id IS NULL OR EXISTS (
              SELECT 1 FROM public.releases_scenariorelease b
              WHERE b.id = NEW.baseline_release_id AND b.organization_id = NEW.organization_id
                AND b.scenario_id = NEW.scenario_id
          ))
       ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PUBLICATION_SCOPE_INVALID';
    END IF;
    IF NEW.completed_at IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM public.releases_scenariorelease r
        JOIN public.catalog_scenario s ON s.id = r.scenario_id
        JOIN public.evaluations_evalrun e ON e.release_id = r.id
        WHERE r.id = NEW.release_id AND e.id = NEW.evaluation_id AND r.status = 'active'
          AND s.status = 'active' AND e.status = 'passed'
          AND e.total_cases > 0 AND e.passed_cases = e.total_cases
          AND (NEW.source_job_id IS NULL OR (
            e.generation_count > 0 AND e.generation_count = (
              SELECT count(*) FROM public.evaluations_evaldatageneration g
              JOIN public.documents_documentsetversion v ON v.id = g.document_set_version_id
              JOIN public.ingestion_indexversion i ON i.id = g.index_version_id
              WHERE g.evaluation_id = e.id AND v.status = 'active' AND i.status = 'active'
                AND v.built_index_version_id = i.id AND i.store_ready
                AND (i.storage_layout = 'legacy' OR i.storage_state = 'sealed')
            )
          ))
          AND e.total_cases = (SELECT count(*) FROM public.evaluations_evalcaseresult c
                               WHERE c.run_id = e.id AND c.passed)
    ) THEN
        RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PUBLICATION_COMPLETION_INVALID';
    END IF;
    RETURN NEW;
END
$body$;
"""


def install(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(AFTER)


def reverse(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT rolsuper OR rolbypassrls FROM pg_roles WHERE rolname = current_user"
            )
            if not cursor.fetchone()[0]:
                raise RuntimeError("SOURCE_PUBLICATION_ROLLBACK_REQUIRES_PRIVILEGED_ROLE")
    if (
        apps.get_model("releases", "ScenarioPublication")
        .objects.filter(source_job__isnull=False)
        .exists()
    ):
        raise RuntimeError("SOURCE_PUBLICATION_ROLLBACK_REQUIRES_EMPTY_HISTORY")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(BEFORE)


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0006_prepared_evaluation"),
        ("workflows", "0021_prepared_evaluation"),
        ("builder", "0008_artifactdraft_model_profile"),
        ("catalog", "0013_durable_retrieval_selection"),
        ("evaluations", "0006_prepared_evaluation"),
        ("ingestion", "0037_resource_source_revisions"),
        ("releases", "0006_scenario_publication"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariopublication",
            name="source_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publications",
                to="ingestion.stagedindexbuildjob",
            ),
        ),
        migrations.AlterField(
            model_name="scenariopublication",
            name="draft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="builder.workflowdraft",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariopublication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("draft__isnull", False), ("source_job__isnull", True)),
                    models.Q(("draft__isnull", True), ("source_job__isnull", False)),
                    _connector="OR",
                ),
                name="publication_single_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariopublication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_job__isnull", False)),
                fields=("source_job", "scenario"),
                name="uniq_source_job_scenario_publication",
            ),
        ),
        migrations.RunPython(install, reverse),
    ]
