# Generated by Django 5.2.16 on 2026-07-11 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0003_alter_artifactversion_type'),
        ('catalog', '0001_initial'),
        ('identity', '0002_consumertoken'),
        ('releases', '0002_releasecanary'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compiled_config', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('compiler_version', models.CharField(default='agent-compiler/v1', max_length=32)),
                ('created_by', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_versions', to='tenancy.organization')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_versions', to='catalog.scenario')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compiled_agents', to='artifacts.artifactversion')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('input_checksum', models.CharField(max_length=64)),
                ('execution_context', models.JSONField()),
                ('start_snapshot', models.JSONField(default=dict)),
                ('checkpoint', models.JSONField(default=dict)),
                ('checkpoint_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('queued', 'Queued'), ('running', 'Running'), ('waiting_approval', 'Waiting approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('timed_out', 'Timed out'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('step_count', models.PositiveIntegerField(default=0)),
                ('tool_call_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('awaiting_step', models.IntegerField(blank=True, null=True)),
                ('awaiting_role', models.CharField(blank=True, max_length=128)),
                ('deadline_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_runs', to='identity.consumer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='tenancy.organization')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_runs', to='releases.scenariorelease')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='catalog.scenario')),
                ('agent_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='agents.agentversion')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('step_index', models.IntegerField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=32)),
                ('outcome', models.CharField(blank=True, max_length=32)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('state_checksum', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.agentrun')),
            ],
            options={
                'ordering': ['run_id', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_agent_run_event_sequence')],
            },
        ),
        migrations.AddConstraint(
            model_name='agentversion',
            constraint=models.UniqueConstraint(fields=('scenario', 'source_artifact', 'compiler_version'), name='uniq_compiled_agent_source'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='agents_agen_organiz_56ac53_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(fields=('consumer', 'idempotency_key'), name='uniq_agent_run_consumer_idempotency'),
        ),
    ]
