# Generated by Django 5.2.16 on 2026-07-17 19:50

import django.db.models.deletion
from django.db import migrations, models

_TABLE = "agents_agentruntimecontrol"


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    quoted = schema_editor.quote_name(_TABLE)
    with schema_editor.connection.cursor() as cursor:
        # Exactly one platform-global (NULL-organization) control row.
        cursor.execute(
            f"""CREATE UNIQUE INDEX IF NOT EXISTS uniq_agent_runtime_control_global
                ON {quoted} ((organization_id IS NULL)) WHERE organization_id IS NULL"""
        )
        # Manual tenant RLS: a tenant scope sees its own org row *and* the global row so the
        # runtime can enforce both from a tenant-scoped session; writes stay scope-bound.
        cursor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
        cursor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
        cursor.execute(
            f"""CREATE POLICY tenant_isolation ON {quoted}
                USING (
                    organization_id IS NULL
                    OR agenthub_tenant_scope_contains(organization_id)
                )
                WITH CHECK (
                    organization_id IS NULL
                    OR agenthub_tenant_scope_contains(organization_id)
                )"""
        )


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    quoted = schema_editor.quote_name(_TABLE)
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
        cursor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
        cursor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")
        cursor.execute("DROP INDEX IF EXISTS uniq_agent_runtime_control_global")


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentrunevent_organization'),
        ('tenancy', '0002_force_tenant_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='checkpoint_version',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='AgentRuntimeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suspended', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_runtime_controls', to='tenancy.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization',), name='uniq_agent_runtime_control_org')],
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
