# Generated by Django 5.2.16 on 2026-07-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('releases', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suite_ref', models.CharField(max_length=256)),
                ('suite_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=16)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('passed_cases', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_by', models.CharField(max_length=200)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_runs', to='tenancy.organization')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_runs', to='releases.scenariorelease')),
            ],
        ),
        migrations.CreateModel(
            name='EvalCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_id', models.CharField(max_length=128)),
                ('passed', models.BooleanField()),
                ('fallback_used', models.BooleanField(default=False)),
                ('assertions', models.JSONField(default=list)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_results', to='evaluations.evalrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='evalrun',
            index=models.Index(fields=['release', 'suite_checksum', 'status'], name='evalrun_gate_lookup'),
        ),
        migrations.AddConstraint(
            model_name='evalcaseresult',
            constraint=models.UniqueConstraint(fields=('run', 'case_id'), name='uniq_case_result_run_case'),
        ),
    ]
