# Generated by Django 5.2.16 on 2026-08-07 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_aiproject_owner_membership'),
        ('evaluations', '0003_question_sets_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='catalog.scenario'),
        ),
    ]
