# Generated by Django 5.2.16 on 2026-08-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_questionset_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncase',
            name='expected_answer',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
