# Generated by Django 5.2.16 on 2026-07-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('consumer', 'Consumer'), ('system', 'System')], max_length=16)),
                ('actor_id', models.CharField(max_length=255)),
                ('organization_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('success', 'Success'), ('failure', 'Failure')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('trace_id', models.CharField(blank=True, max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
