# Generated by Django 5.2.16 on 2026-07-10 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0002_alter_artifactversion_type'),
        ('catalog', '0001_initial'),
        ('identity', '0002_consumertoken'),
        ('releases', '0002_releasecanary'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compiled_graph', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('compiler_version', models.CharField(default='workflow-compiler/v1', max_length=32)),
                ('created_by', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_versions', to='tenancy.organization')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_versions', to='catalog.scenario')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compiled_workflows', to='artifacts.artifactversion')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('input_checksum', models.CharField(max_length=64)),
                ('execution_context', models.JSONField()),
                ('redacted_state', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('timed_out', 'Timed out'), ('cancelled', 'Cancelled')], default='requested', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('deadline_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_runs', to='identity.consumer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='tenancy.organization')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_runs', to='releases.scenariorelease')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='catalog.scenario')),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='workflows.workflowversion')),
            ],
        ),
        migrations.CreateModel(
            name='CustomNodeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logical_id', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField()),
                ('manifest', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('installed_package_version', models.CharField(max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_node_definitions', to='tenancy.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'logical_id', 'version'), name='uniq_custom_node_org_logical_version')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('node_id', models.CharField(blank=True, max_length=64)),
                ('outcome', models.CharField(blank=True, max_length=32)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('state_checksum', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflows.workflowrun')),
            ],
            options={
                'ordering': ['run_id', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_run_event_sequence')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowversion',
            constraint=models.UniqueConstraint(fields=('scenario', 'source_artifact', 'compiler_version'), name='uniq_compiled_workflow_source'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='workflows_w_organiz_9bcc06_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowrun',
            constraint=models.UniqueConstraint(fields=('consumer', 'idempotency_key'), name='uniq_workflow_run_consumer_idempotency'),
        ),
    ]
