# Generated by Django 5.2.16 on 2026-07-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='awaiting_node',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('queued', 'Queued'), ('running', 'Running'), ('waiting_approval', 'Waiting approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('timed_out', 'Timed out'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
