# Generated by Django 5.2.16 on 2026-07-17 09:09

import django.db.models.deletion
from django.db import migrations, models


RLS_SQL = """
ALTER TABLE workflows_workflowbranch ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflows_workflowbranch FORCE ROW LEVEL SECURITY;
CREATE POLICY workflowbranch_tenant_scope ON workflows_workflowbranch
  USING (agenthub_tenant_scope_contains(organization_id))
  WITH CHECK (agenthub_tenant_scope_contains(organization_id));
ALTER TABLE workflows_workflowjoin ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflows_workflowjoin FORCE ROW LEVEL SECURITY;
CREATE POLICY workflowjoin_tenant_scope ON workflows_workflowjoin
  USING (agenthub_tenant_scope_contains(organization_id))
  WITH CHECK (agenthub_tenant_scope_contains(organization_id));
"""

RLS_REVERSE_SQL = """
DROP POLICY IF EXISTS workflowjoin_tenant_scope ON workflows_workflowjoin;
ALTER TABLE workflows_workflowjoin DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS workflowbranch_tenant_scope ON workflows_workflowbranch;
ALTER TABLE workflows_workflowbranch DISABLE ROW LEVEL SECURITY;
"""


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(RLS_SQL)


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(RLS_REVERSE_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_force_tenant_rls"),
        ("workflows", "0003_workflowrunevent_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("region_node_id", models.CharField(max_length=64)),
                ("branch_name", models.CharField(max_length=64)),
                ("item_ordinal", models.PositiveIntegerField(default=0)),
                ("workflow_checksum", models.CharField(max_length=64)),
                ("transition_version", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("input_state", models.JSONField(default=dict)),
                ("result_state", models.JSONField(default=dict)),
                ("result_checksum", models.CharField(blank=True, max_length=64)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy.organization"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="workflows.workflowrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "created_at"],
                        name="workflows_w_organiz_9f1ab9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "region_node_id", "branch_name", "item_ordinal"),
                        name="uniq_workflow_branch_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt_count__lte", 3)),
                        name="workflow_branch_attempt_lte_3",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowJoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("region_node_id", models.CharField(max_length=64)),
                ("join_node_id", models.CharField(max_length=64)),
                ("workflow_checksum", models.CharField(max_length=64)),
                ("transition_version", models.CharField(max_length=32)),
                ("mode", models.CharField(max_length=16)),
                ("required_count", models.PositiveIntegerField()),
                ("branch_count", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("merged_state", models.JSONField(default=dict)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy.organization"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joins",
                        to="workflows.workflowrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "created_at"],
                        name="workflows_w_organiz_f53d6f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "region_node_id"), name="uniq_workflow_join_region"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("required_count__gte", 1)),
                        name="workflow_join_required_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("branch_count__gte", 1)),
                        name="workflow_join_branch_count_gte_1",
                    ),
                ],
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
