# Generated by Django 5.2.16 on 2026-07-17 08:22

import django.db.models.deletion
from django.db import migrations, models


def enable_child_link_rls(apps, schema_editor):
    # Provision FORCE RLS on the new tenant-owned link table (ADR-0004), matching the
    # tenancy.0002 pattern. The shared ``agenthub_tenant_scope_contains`` function already exists.
    if schema_editor.connection.vendor != "postgresql":
        return
    quoted = schema_editor.quote_name("workflows_workflowchildlink")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
        cursor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
        cursor.execute(
            f"""CREATE POLICY tenant_isolation ON {quoted}
            USING (agenthub_tenant_scope_contains(organization_id))
            WITH CHECK (agenthub_tenant_scope_contains(organization_id))"""
        )


def disable_child_link_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    quoted = schema_editor.quote_name("workflows_workflowchildlink")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
        cursor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
        cursor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    # Depend only on the minimal migrations that create the referenced tables (Scenario exists at
    # catalog 0002). Do NOT depend on later catalog leaves: the phase-2.5 migration-rollback tests
    # migrate catalog back to 0002, and a dependency on a later catalog migration would unapply this
    # table (and not re-apply it), leaving the child-link table missing for subsequent tests.
    dependencies = [
        ('agents', '0002_agentrunevent_organization'),
        ('catalog', '0002_scenario_organization'),
        ('releases', '0003_direct_tenant_lineage'),
        ('tenancy', '0002_force_tenant_rls'),
        ('workflows', '0005_workflowwait_durable_wait_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('queued', 'Queued'), ('running', 'Running'), ('waiting_approval', 'Waiting approval'), ('waiting_event', 'Waiting event'), ('waiting_human', 'Waiting human'), ('waiting_timer', 'Waiting timer'), ('waiting_child', 'Waiting child'), ('completed', 'Completed'), ('failed', 'Failed'), ('timed_out', 'Timed out'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkflowChildLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_site', models.CharField(max_length=64)),
                ('child_kind', models.CharField(max_length=16)),
                ('child_release_checksum', models.CharField(max_length=64)),
                ('child_artifact_checksum', models.CharField(max_length=64)),
                ('child_public_ref', models.CharField(blank=True, max_length=64)),
                ('effective_capability_checksum', models.CharField(max_length=64)),
                ('depth', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='admitted', max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('child_agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_link', to='agents.agentrun')),
                ('child_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_child_links', to='releases.scenariorelease')),
                ('child_scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_child_links', to='catalog.scenario')),
                ('child_workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_child_workflow_link', to='workflows.workflowrun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_child_links', to='tenancy.organization')),
                ('parent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='workflows.workflowrun')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='workflows_w_organiz_a2a08e_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent_run', 'call_site'), name='uniq_child_link_parent_call_site')],
            },
        ),
        migrations.RunPython(enable_child_link_rls, disable_child_link_rls),
    ]
