# Generated by Django 5.2.16 on 2026-07-17 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


RECOVERY_TABLES = (
    "workflows_workflownodeattempt",
    "workflows_workflowcompensationentry",
    "workflows_workflowrecoverycase",
    "workflows_workflowrecoveryapproval",
)


def enable_recovery_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RECOVERY_TABLES:
            quoted = schema_editor.quote_name(table)
            cursor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
            cursor.execute(
                f"""CREATE POLICY tenant_isolation ON {quoted}
                USING (agenthub_tenant_scope_contains(organization_id))
                WITH CHECK (agenthub_tenant_scope_contains(organization_id))"""
            )


def disable_recovery_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RECOVERY_TABLES:
            quoted = schema_editor.quote_name(table)
            cursor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
            cursor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_force_tenant_rls'),
        ('workflows', '0006_alter_workflowrun_status_workflowchildlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRecoveryCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('node_id', models.CharField(max_length=64)),
                ('failure_class', models.CharField(max_length=24)),
                ('reason_code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_second_approval', 'Awaiting second approval'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('state_checksum', models.CharField(max_length=64)),
                ('high_risk', models.BooleanField(default=False)),
                ('required_approvals', models.PositiveSmallIntegerField(default=1)),
                ('resolved_action', models.CharField(blank=True, max_length=40)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_recovery_cases', to='tenancy.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_cases', to='workflows.workflowrun')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRecoveryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(max_length=40)),
                ('reason', models.CharField(max_length=200)),
                ('revision', models.PositiveIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_recovery_approvals', to='tenancy.organization')),
                ('recovery_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflows.workflowrecoverycase')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowCompensationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('source_node_id', models.CharField(max_length=64)),
                ('compensation_node_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('input_checksum', models.CharField(max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_compensation_entries', to='tenancy.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_entries', to='workflows.workflowrun')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status', 'created_at'], name='workflows_w_organiz_10db52_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_workflow_compensation_run_sequence')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_id', models.CharField(max_length=64)),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('retry_wait', 'Retry waiting'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=16)),
                ('failure_class', models.CharField(blank=True, max_length=24)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('state_checksum', models.CharField(blank=True, max_length=64)),
                ('retry_not_before', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_node_attempts', to='tenancy.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_attempts', to='workflows.workflowrun')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status', 'retry_not_before'], name='workflows_w_organiz_0ee153_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'node_id', 'ordinal'), name='uniq_workflow_attempt_run_node_ordinal')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowrecoverycase',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='workflows_w_organiz_779450_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowrecoverycase',
            constraint=models.UniqueConstraint(fields=('run', 'node_id', 'revision'), name='uniq_recovery_run_node_revision'),
        ),
        migrations.AddConstraint(
            model_name='workflowrecoverycase',
            constraint=models.CheckConstraint(condition=models.Q(('required_approvals__in', [1, 2])), name='workflow_recovery_required_approvals_valid'),
        ),
        migrations.AddConstraint(
            model_name='workflowrecoveryapproval',
            constraint=models.UniqueConstraint(fields=('recovery_case', 'actor_id'), name='uniq_recovery_case_actor'),
        ),
        migrations.RunPython(enable_recovery_rls, disable_recovery_rls),
    ]
