# Generated by Django 5.2.16 on 2026-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_failure_retry_compensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('queued', 'Queued'), ('running', 'Running'), ('waiting_approval', 'Waiting approval'), ('waiting_event', 'Waiting event'), ('waiting_human', 'Waiting human'), ('waiting_timer', 'Waiting timer'), ('waiting_child', 'Waiting child'), ('recovery_required', 'Recovery required'), ('completed', 'Completed'), ('failed', 'Failed'), ('timed_out', 'Timed out'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
