# Generated by Django 5.2.16 on 2026-07-24

import uuid

import django.db.models.deletion
from django.db import migrations, models

_TABLES = ("workflows_run", "workflows_runevent")


def enable_unified_run_rls(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in _TABLES:
            quoted = schema_editor.quote_name(table)
            cursor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
            cursor.execute(
                f"""CREATE POLICY tenant_isolation ON {quoted}
                USING (agenthub_tenant_scope_contains(organization_id))
                WITH CHECK (agenthub_tenant_scope_contains(organization_id))"""
            )


def disable_unified_run_rls(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in _TABLES:
            quoted = schema_editor.quote_name(table)
            cursor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
            cursor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_aiproject_owner_membership"),
        ("identity", "0008_delegated_assignments"),
        ("releases", "0003_direct_tenant_lineage"),
        ("tenancy", "0003_document_manager_role"),
        ("workflows", "0008_recovery_required_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_id", models.CharField(max_length=200)),
                (
                    "response_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("compiled_checksum", models.CharField(max_length=64)),
                ("compiler_version", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("waiting_approval", "Waiting approval"),
                            ("waiting_event", "Waiting event"),
                            ("waiting_human", "Waiting human"),
                            ("waiting_timer", "Waiting timer"),
                            ("waiting_child", "Waiting child"),
                            ("recovery_required", "Recovery required"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timed_out", "Timed out"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[("sync", "Synchronous"), ("background", "Background")],
                        max_length=16,
                    ),
                ),
                ("checkpoint", models.JSONField(default=dict)),
                ("checkpoint_version", models.PositiveIntegerField(default=1)),
                ("next_event_sequence", models.PositiveBigIntegerField(default=1)),
                (
                    "awaiting_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approval", "Approval"),
                            ("event", "Event"),
                            ("human", "Human"),
                            ("timer", "Timer"),
                            ("child", "Child"),
                            ("recovery", "Recovery"),
                        ],
                        max_length=16,
                    ),
                ),
                ("awaiting_reference", models.CharField(blank=True, max_length=200)),
                ("deadline_at", models.DateTimeField()),
                ("sync_lease_token", models.UUIDField(blank=True, null=True)),
                ("sync_lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_state",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("requested", "Requested"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("cancellation_requested_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason_code", models.CharField(blank=True, max_length=64)),
                ("step_count", models.PositiveIntegerField(default=0)),
                ("tool_call_count", models.PositiveIntegerField(default=0)),
                ("input_token_count", models.PositiveIntegerField(default=0)),
                ("output_token_count", models.PositiveIntegerField(default=0)),
                ("input_checksum", models.CharField(max_length=64)),
                ("execution_context", models.JSONField(default=dict)),
                ("redacted_state", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="identity.consumer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="releases.scenariorelease",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="catalog.scenario",
                    ),
                ),
                (
                    "workflow_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unified_runs",
                        to="workflows.workflowversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("run.requested", "Run requested"),
                            ("run.queued", "Run queued"),
                            ("run.started", "Run started"),
                            ("run.checkpointed", "Run checkpointed"),
                            ("run.waiting", "Run waiting"),
                            ("run.resumed", "Run resumed"),
                            ("run.cancellation_requested", "Cancellation requested"),
                            ("run.recovery_required", "Recovery required"),
                            ("run.completed", "Run completed"),
                            ("run.failed", "Run failed"),
                            ("run.timed_out", "Run timed out"),
                            ("run.cancelled", "Run cancelled"),
                            ("run.late_result_discarded", "Late result discarded"),
                        ],
                        max_length=64,
                    ),
                ),
                ("node_id", models.CharField(blank=True, max_length=64)),
                ("outcome", models.CharField(blank=True, max_length=32)),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("state_checksum", models.CharField(blank=True, max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_events",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="workflows.run",
                    ),
                ),
            ],
            options={"ordering": ["run_id", "sequence"]},
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["organization", "status", "created_at"],
                name="workflows_r_organiz_2cdee4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["organization", "execution_mode", "created_at"],
                name="workflows_r_organiz_4d32e3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.UniqueConstraint(
                fields=("consumer", "idempotency_key"),
                name="uniq_run_consumer_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(
                condition=models.Q(("checkpoint_version__gte", 1)),
                name="run_checkpoint_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.CheckConstraint(
                condition=models.Q(("next_event_sequence__gte", 1)),
                name="run_next_event_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="runevent",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="uniq_unified_run_event_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="runevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)),
                name="run_event_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="runevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        [
                            "run.requested",
                            "run.queued",
                            "run.started",
                            "run.checkpointed",
                            "run.waiting",
                            "run.resumed",
                            "run.cancellation_requested",
                            "run.recovery_required",
                            "run.completed",
                            "run.failed",
                            "run.timed_out",
                            "run.cancelled",
                            "run.late_result_discarded",
                        ],
                    )
                ),
                name="run_event_type_valid",
            ),
        ),
        migrations.RunPython(enable_unified_run_rls, disable_unified_run_rls),
    ]
