# Generated by Django 5.2.16 on 2026-07-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0003_document_manager_role"),
        ("workflows", "0009_unified_run_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="runevent",
            name="transition_checksum",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="runevent",
            name="transition_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="runevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transition_token__isnull", False)),
                fields=("run", "transition_token"),
                name="uniq_run_event_transition_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="runevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("transition_checksum", ""), ("transition_token__isnull", True)),
                    models.Q(
                        ("transition_token__isnull", False),
                        models.Q(("transition_checksum", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="run_event_transition_token_checksum_pair",
            ),
        ),
    ]
