# Generated by Django 5.2.16 on 2026-07-24 15:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


def enable_run_wait_rls(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    quoted = schema_editor.quote_name("workflows_runwait")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
        cursor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
        cursor.execute(
            f"""CREATE POLICY tenant_isolation ON {quoted}
            USING (agenthub_tenant_scope_contains(organization_id))
            WITH CHECK (agenthub_tenant_scope_contains(organization_id))"""
        )


def disable_run_wait_rls(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    quoted = schema_editor.quote_name("workflows_runwait")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
        cursor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
        cursor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0003_document_manager_role"),
        ("workflows", "0011_run_background_claim"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunWait",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("approval", "Approval"),
                            ("event", "Event"),
                            ("human", "Human"),
                            ("timer", "Timer"),
                            ("child", "Child"),
                        ],
                        max_length=16,
                    ),
                ),
                ("node_id", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resumed", "Resumed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("resume_token_hash", models.CharField(max_length=64, unique=True)),
                ("pending_checksum", models.CharField(max_length=64)),
                ("checkpoint_version_snapshot", models.PositiveIntegerField()),
                ("release_id_snapshot", models.PositiveBigIntegerField()),
                ("compiled_checksum", models.CharField(max_length=64)),
                ("compiler_version", models.CharField(max_length=32)),
                ("payload_schema", models.JSONField(blank=True, default=dict)),
                ("output_mapping", models.JSONField(blank=True, default=list)),
                ("requester_actor_id", models.CharField(max_length=200)),
                ("allowed_roles", models.JSONField(blank=True, default=list)),
                ("deny_self_decision", models.BooleanField(default=True)),
                ("deadline_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_by", models.CharField(blank=True, max_length=200)),
                ("resume_checksum", models.CharField(blank=True, max_length=64)),
                ("result_checkpoint_version", models.PositiveIntegerField(blank=True, null=True)),
                ("redacted_payload", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_waits",
                        to="tenancy.organization",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waits",
                        to="workflows.run",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "deadline_at"],
                        name="workflows_r_organiz_c93997_idx",
                    ),
                    models.Index(
                        fields=["run", "created_at"], name="workflows_r_run_id_9218cc_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("run",),
                        name="uniq_pending_run_wait",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("consumed_at__isnull", True),
                                ("consumed_by", ""),
                                ("result_checkpoint_version__isnull", True),
                                ("resume_checksum", ""),
                                ("status", "pending"),
                            ),
                            models.Q(
                                ("consumed_at__isnull", False),
                                ("result_checkpoint_version__isnull", False),
                                ("resume_checksum__gt", ""),
                                ("status", "resumed"),
                            ),
                            models.Q(
                                ("consumed_at__isnull", False),
                                ("result_checkpoint_version__isnull", True),
                                ("status__in", ["expired", "cancelled"]),
                            ),
                            _connector="OR",
                        ),
                        name="run_wait_consumption_complete",
                    ),
                ],
            },
        ),
        migrations.RunPython(enable_run_wait_rls, disable_run_wait_rls),
    ]
