# Generated by Django 5.2.16 on 2026-07-27 14:05

import uuid

import django.db.models.deletion
from django.db import migrations, models

RUN_REGION_TABLES = ("workflows_runbranch", "workflows_runjoin")


def enable_run_region_rls(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RUN_REGION_TABLES:
            quoted = schema_editor.quote_name(table)
            cursor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
            cursor.execute(
                f"""CREATE POLICY tenant_isolation ON {quoted}
                USING (agenthub_tenant_scope_contains(organization_id))
                WITH CHECK (agenthub_tenant_scope_contains(organization_id))"""
            )


def disable_run_region_rls(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in RUN_REGION_TABLES:
            quoted = schema_editor.quote_name(table)
            cursor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
            cursor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):
    dependencies = [
        ('tenancy', '0003_document_manager_role'),
        ('workflows', '0012_run_wait'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunBranch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_node_id', models.CharField(max_length=64)),
                ('branch_name', models.CharField(max_length=64)),
                ('item_ordinal', models.PositiveIntegerField(default=0)),
                ('compiled_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('input_state', models.JSONField(default=dict)),
                ('result_state', models.JSONField(default=dict)),
                ('result_checksum', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('delivery_token', models.UUIDField(blank=True, null=True)),
                ('delivery_expires_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunJoin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_node_id', models.CharField(max_length=64)),
                ('join_node_id', models.CharField(max_length=64)),
                ('compiled_checksum', models.CharField(max_length=64)),
                ('mode', models.CharField(max_length=16)),
                ('required_count', models.PositiveIntegerField()),
                ('branch_count', models.PositiveIntegerField()),
                ('max_concurrency', models.PositiveSmallIntegerField()),
                ('max_duration_seconds', models.PositiveIntegerField()),
                ('max_state_bytes', models.PositiveIntegerField()),
                ('deadline_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('merged_state', models.JSONField(default=dict)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='runevent',
            name='run_event_type_valid',
        ),
        migrations.AlterField(
            model_name='runevent',
            name='event_type',
            field=models.CharField(choices=[('run.requested', 'Run requested'), ('run.queued', 'Run queued'), ('run.started', 'Run started'), ('run.checkpointed', 'Run checkpointed'), ('run.waiting', 'Run waiting'), ('run.resumed', 'Run resumed'), ('run.branches_opened', 'Run branches opened'), ('run.join_closed', 'Run join closed'), ('run.cancellation_requested', 'Cancellation requested'), ('run.recovery_required', 'Recovery required'), ('run.completed', 'Run completed'), ('run.failed', 'Run failed'), ('run.timed_out', 'Run timed out'), ('run.cancelled', 'Run cancelled'), ('run.late_result_discarded', 'Late result discarded')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='runevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['run.requested', 'run.queued', 'run.started', 'run.checkpointed', 'run.waiting', 'run.resumed', 'run.branches_opened', 'run.join_closed', 'run.cancellation_requested', 'run.recovery_required', 'run.completed', 'run.failed', 'run.timed_out', 'run.cancelled', 'run.late_result_discarded'])), name='run_event_type_valid'),
        ),
        migrations.AddField(
            model_name='runbranch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_branches', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='runbranch',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='workflows.run'),
        ),
        migrations.AddField(
            model_name='runjoin',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_joins', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='runjoin',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joins', to='workflows.run'),
        ),
        migrations.AddIndex(
            model_name='runbranch',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='workflows_r_organiz_26f0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='runbranch',
            index=models.Index(fields=['run', 'region_node_id'], name='workflows_r_run_id_144700_idx'),
        ),
        migrations.AddIndex(
            model_name='runbranch',
            index=models.Index(fields=['organization', 'status', 'delivery_expires_at'], name='run_branch_dispatch_idx'),
        ),
        migrations.AddConstraint(
            model_name='runbranch',
            constraint=models.UniqueConstraint(fields=('run', 'region_node_id', 'branch_name', 'item_ordinal'), name='uniq_run_branch_identity'),
        ),
        migrations.AddConstraint(
            model_name='runbranch',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__lte', 3)), name='run_branch_attempt_bounded'),
        ),
        migrations.AddConstraint(
            model_name='runbranch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'running']), ('finished_at__isnull', False), _connector='OR'), name='run_branch_terminal_finished'),
        ),
        migrations.AddIndex(
            model_name='runjoin',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='workflows_r_organiz_13c9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='runjoin',
            index=models.Index(fields=['organization', 'status', 'deadline_at'], name='run_join_deadline_idx'),
        ),
        migrations.AddConstraint(
            model_name='runjoin',
            constraint=models.UniqueConstraint(fields=('run', 'region_node_id'), name='uniq_run_join_region'),
        ),
        migrations.AddConstraint(
            model_name='runjoin',
            constraint=models.UniqueConstraint(fields=('run', 'join_node_id'), name='uniq_run_join_node'),
        ),
        migrations.AddConstraint(
            model_name='runjoin',
            constraint=models.CheckConstraint(condition=models.Q(('required_count__gte', 1)), name='run_join_required_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='runjoin',
            constraint=models.CheckConstraint(condition=models.Q(('branch_count__gte', 1)), name='run_join_branch_count_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='runjoin',
            constraint=models.CheckConstraint(condition=models.Q(('required_count__lte', models.F('branch_count'))), name='run_join_required_lte_branches'),
        ),
        migrations.AddConstraint(
            model_name='runjoin',
            constraint=models.CheckConstraint(condition=models.Q(('max_concurrency__gte', 1), ('max_concurrency__lte', 16)), name='run_join_concurrency_bounded'),
        ),
        migrations.AddConstraint(
            model_name='runjoin',
            constraint=models.CheckConstraint(condition=models.Q(('max_duration_seconds__gte', 1), ('max_duration_seconds__lte', 300)), name='run_join_duration_bounded'),
        ),
        migrations.AddConstraint(
            model_name='runjoin',
            constraint=models.CheckConstraint(condition=models.Q(('max_state_bytes__gte', 1), ('max_state_bytes__lte', 1048576)), name='run_join_state_bounded'),
        ),
        migrations.AddConstraint(
            model_name='runjoin',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'open'), ('closed_at__isnull', False), _connector='OR'), name='run_join_closed_at_set'),
        ),
        migrations.RunPython(enable_run_region_rls, disable_run_region_rls),
    ]
