# Generated by Django 5.2.16 on 2026-07-28 03:34

import django.db.models.deletion
from django.db import migrations, models


def enable_run_child_rls(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    quoted = schema_editor.quote_name("workflows_runchildlink")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
        cursor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
        cursor.execute(
            f"""CREATE POLICY tenant_isolation ON {quoted}
            USING (agenthub_tenant_scope_contains(organization_id))
            WITH CHECK (agenthub_tenant_scope_contains(organization_id))"""
        )


def disable_run_child_rls(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    quoted = schema_editor.quote_name("workflows_runchildlink")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
        cursor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
        cursor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_document_manager_role'),
        ('workflows', '0014_remove_workflowchildlink_child_agent_run_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunChildLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_site', models.CharField(max_length=64)),
                ('child_release_checksum', models.CharField(max_length=64)),
                ('child_artifact_checksum', models.CharField(max_length=64)),
                ('effective_capability_checksum', models.CharField(max_length=64)),
                ('depth', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='admitted', max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='runevent',
            name='run_event_type_valid',
        ),
        migrations.AlterField(
            model_name='runevent',
            name='event_type',
            field=models.CharField(choices=[('run.requested', 'Run requested'), ('run.queued', 'Run queued'), ('run.started', 'Run started'), ('run.checkpointed', 'Run checkpointed'), ('run.waiting', 'Run waiting'), ('run.resumed', 'Run resumed'), ('run.branches_opened', 'Run branches opened'), ('run.join_closed', 'Run join closed'), ('run.child_admitted', 'Child run admitted'), ('run.child_completed', 'Child run completed'), ('run.cancellation_requested', 'Cancellation requested'), ('run.recovery_required', 'Recovery required'), ('run.completed', 'Run completed'), ('run.failed', 'Run failed'), ('run.timed_out', 'Run timed out'), ('run.cancelled', 'Run cancelled'), ('run.late_result_discarded', 'Late result discarded')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='runevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['run.requested', 'run.queued', 'run.started', 'run.checkpointed', 'run.waiting', 'run.resumed', 'run.branches_opened', 'run.join_closed', 'run.child_admitted', 'run.child_completed', 'run.cancellation_requested', 'run.recovery_required', 'run.completed', 'run.failed', 'run.timed_out', 'run.cancelled', 'run.late_result_discarded'])), name='run_event_type_valid'),
        ),
        migrations.AddField(
            model_name='runchildlink',
            name='child_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parent_link', to='workflows.run'),
        ),
        migrations.AddField(
            model_name='runchildlink',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_child_links', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='runchildlink',
            name='parent_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='workflows.run'),
        ),
        migrations.AddIndex(
            model_name='runchildlink',
            index=models.Index(fields=['organization', 'status'], name='workflows_r_organiz_26496b_idx'),
        ),
        migrations.AddConstraint(
            model_name='runchildlink',
            constraint=models.UniqueConstraint(fields=('parent_run', 'call_site'), name='uniq_run_child_parent_call_site'),
        ),
        migrations.RunPython(enable_run_child_rls, disable_run_child_rls),
    ]
