# Generated by Django 5.2.16 on 2026-07-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_document_manager_role'),
        ('workflows', '0015_run_child_link'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='runevent',
            name='run_event_type_valid',
        ),
        migrations.AlterField(
            model_name='runevent',
            name='event_type',
            field=models.CharField(choices=[('run.requested', 'Run requested'), ('run.queued', 'Run queued'), ('run.started', 'Run started'), ('run.checkpointed', 'Run checkpointed'), ('run.waiting', 'Run waiting'), ('run.resumed', 'Run resumed'), ('run.branches_opened', 'Run branches opened'), ('run.join_closed', 'Run join closed'), ('run.child_admitted', 'Child run admitted'), ('run.child_completed', 'Child run completed'), ('run.node_retried', 'Node retried'), ('run.cancellation_requested', 'Cancellation requested'), ('run.recovery_required', 'Recovery required'), ('run.completed', 'Run completed'), ('run.failed', 'Run failed'), ('run.timed_out', 'Run timed out'), ('run.cancelled', 'Run cancelled'), ('run.late_result_discarded', 'Late result discarded')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='runevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['run.requested', 'run.queued', 'run.started', 'run.checkpointed', 'run.waiting', 'run.resumed', 'run.branches_opened', 'run.join_closed', 'run.child_admitted', 'run.child_completed', 'run.node_retried', 'run.cancellation_requested', 'run.recovery_required', 'run.completed', 'run.failed', 'run.timed_out', 'run.cancelled', 'run.late_result_discarded'])), name='run_event_type_valid'),
        ),
    ]
