# Generated by Django 5.2.16 on 2026-07-28 03:41

import django.db.models.deletion
from django.db import migrations, models


def enable_run_compensation_rls(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    quoted = schema_editor.quote_name("workflows_runcompensationentry")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"ALTER TABLE {quoted} ENABLE ROW LEVEL SECURITY")
        cursor.execute(f"ALTER TABLE {quoted} FORCE ROW LEVEL SECURITY")
        cursor.execute(
            f"""CREATE POLICY tenant_isolation ON {quoted}
            USING (agenthub_tenant_scope_contains(organization_id))
            WITH CHECK (agenthub_tenant_scope_contains(organization_id))"""
        )


def disable_run_compensation_rls(apps, schema_editor) -> None:
    if schema_editor.connection.vendor != "postgresql":
        return
    quoted = schema_editor.quote_name("workflows_runcompensationentry")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {quoted}")
        cursor.execute(f"ALTER TABLE {quoted} NO FORCE ROW LEVEL SECURITY")
        cursor.execute(f"ALTER TABLE {quoted} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_document_manager_role'),
        ('workflows', '0016_run_retry_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunCompensationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('source_node_id', models.CharField(max_length=64)),
                ('compensation_node_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='runevent',
            name='run_event_type_valid',
        ),
        migrations.AlterField(
            model_name='runevent',
            name='event_type',
            field=models.CharField(choices=[('run.requested', 'Run requested'), ('run.queued', 'Run queued'), ('run.started', 'Run started'), ('run.checkpointed', 'Run checkpointed'), ('run.waiting', 'Run waiting'), ('run.resumed', 'Run resumed'), ('run.branches_opened', 'Run branches opened'), ('run.join_closed', 'Run join closed'), ('run.child_admitted', 'Child run admitted'), ('run.child_completed', 'Child run completed'), ('run.node_retried', 'Node retried'), ('run.compensation', 'Run compensation'), ('run.cancellation_requested', 'Cancellation requested'), ('run.recovery_required', 'Recovery required'), ('run.completed', 'Run completed'), ('run.failed', 'Run failed'), ('run.timed_out', 'Run timed out'), ('run.cancelled', 'Run cancelled'), ('run.late_result_discarded', 'Late result discarded')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='runevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['run.requested', 'run.queued', 'run.started', 'run.checkpointed', 'run.waiting', 'run.resumed', 'run.branches_opened', 'run.join_closed', 'run.child_admitted', 'run.child_completed', 'run.node_retried', 'run.compensation', 'run.cancellation_requested', 'run.recovery_required', 'run.completed', 'run.failed', 'run.timed_out', 'run.cancelled', 'run.late_result_discarded'])), name='run_event_type_valid'),
        ),
        migrations.AddField(
            model_name='runcompensationentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_compensations', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='runcompensationentry',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='workflows.run'),
        ),
        migrations.AddIndex(
            model_name='runcompensationentry',
            index=models.Index(fields=['organization', 'status'], name='workflows_r_organiz_c50387_idx'),
        ),
        migrations.AddConstraint(
            model_name='runcompensationentry',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_run_compensation_sequence'),
        ),
        migrations.AddConstraint(
            model_name='runcompensationentry',
            constraint=models.UniqueConstraint(fields=('run', 'source_node_id'), name='uniq_run_compensation_source'),
        ),
        migrations.RunPython(enable_run_compensation_rls, disable_run_compensation_rls),
    ]
