# Generated by Django 5.2.16 on 2026-07-31 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0017_run_compensation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runwait',
            name='allowed_roles',
        ),
        migrations.RemoveField(
            model_name='runwait',
            name='deny_self_decision',
        ),
    ]
