# Generated by Django 5.2.17 on 2026-09-10 04:27

import django.db.models.deletion
from django.db import migrations, models


def protect_run_revision(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
      CREATE FUNCTION public.agenthub_run_revision_pins() RETURNS trigger
      LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
      DECLARE contract text;
      BEGIN
        IF TG_OP = 'UPDATE' AND OLD.scenario_revision_id IS NOT NULL AND (
          NEW.organization_id, NEW.scenario_id, NEW.release_id, NEW.workflow_version_id,
          NEW.scenario_revision_id, NEW.compiled_checksum, NEW.compiler_version, NEW.consumer_id
        ) IS DISTINCT FROM (
          OLD.organization_id, OLD.scenario_id, OLD.release_id, OLD.workflow_version_id,
          OLD.scenario_revision_id, OLD.compiled_checksum, OLD.compiler_version, OLD.consumer_id
        ) THEN
          RAISE EXCEPTION 'RUN_REVISION_PINS_IMMUTABLE' USING ERRCODE = '23514';
        END IF;
        SELECT execution_contract INTO contract FROM public.releases_scenariorelease
        WHERE id = NEW.release_id;
        IF contract = 'scenario-revision/v1' THEN
          IF NEW.scenario_revision_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM public.releases_scenariorevision v
            WHERE v.id = NEW.scenario_revision_id AND v.organization_id = NEW.organization_id
              AND v.scenario_id = NEW.scenario_id AND v.source_release_id = NEW.release_id
              AND v.workflow_version_id = NEW.workflow_version_id
              AND v.snapshot->'workflow'->>'checksum' = NEW.compiled_checksum
              AND v.snapshot->'workflow'->>'compiler_version' = NEW.compiler_version
              AND NEW.compiler_version = 'workflow-compiler/v7'
          ) THEN
            RAISE EXCEPTION 'RUN_REVISION_SCOPE_INVALID' USING ERRCODE = '23514';
          END IF;
        ELSIF NEW.scenario_revision_id IS NOT NULL THEN
          RAISE EXCEPTION 'RUN_REVISION_SCOPE_INVALID' USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER run_revision_pins BEFORE INSERT OR UPDATE
      ON public.workflows_run FOR EACH ROW EXECUTE FUNCTION public.agenthub_run_revision_pins();
    """)


def unprotect_run_revision(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
      DROP TRIGGER run_revision_pins ON public.workflows_run;
      DROP FUNCTION public.agenthub_run_revision_pins();
    """)


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0005_execution_revision_binding"),
        ("workflows", "0018_remove_runwait_allowed_roles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="scenario_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="releases.scenariorevision",
            ),
        ),
        migrations.RunPython(protect_run_revision, unprotect_run_revision),
    ]
