# Generated by Django 5.2.17 on 2026-09-10 05:08

import django.db.models.deletion
from django.db import migrations, models


def protect_selection(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in ("workflows_runretrievalselection", "workflows_runretrievalgeneration"):
        schema_editor.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")
        schema_editor.execute(f"ALTER TABLE public.{table} FORCE ROW LEVEL SECURITY")
        schema_editor.execute(f"""CREATE POLICY tenant_isolation ON public.{table}
            USING (agenthub_tenant_scope_contains(organization_id))
            WITH CHECK (agenthub_tenant_scope_contains(organization_id))""")
    schema_editor.execute("""
      CREATE FUNCTION public.agenthub_retrieval_selection_integrity() RETURNS trigger
      LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
      BEGIN
        IF TG_OP <> 'INSERT' THEN
          RAISE EXCEPTION 'RETRIEVAL_SELECTION_IMMUTABLE' USING ERRCODE = '23514';
        END IF;
        IF NEW.criteria_checksum !~ '^[0-9a-f]{64}$' OR length(NEW.step_key) = 0
          OR NOT EXISTS (
            SELECT 1 FROM public.workflows_run r
            JOIN public.releases_scenariorevision v ON v.id = r.scenario_revision_id
            WHERE r.id = NEW.run_id AND r.organization_id = NEW.organization_id
              AND v.id = NEW.revision_id AND v.organization_id = NEW.organization_id
              AND v.snapshot->'data'->>'selection' = 'active_generation'
          ) THEN
          RAISE EXCEPTION 'RETRIEVAL_SELECTION_SCOPE_INVALID' USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER retrieval_selection_integrity BEFORE INSERT OR UPDATE OR DELETE
      ON public.workflows_runretrievalselection FOR EACH ROW
      EXECUTE FUNCTION public.agenthub_retrieval_selection_integrity();

      CREATE FUNCTION public.agenthub_retrieval_generation_integrity() RETURNS trigger
      LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
      BEGIN
        IF TG_OP <> 'INSERT' THEN
          RAISE EXCEPTION 'RETRIEVAL_SELECTION_IMMUTABLE' USING ERRCODE = '23514';
        END IF;
        PERFORM 1 FROM public.documents_documentset WHERE id = NEW.document_set_id FOR SHARE;
        PERFORM 1 FROM public.ingestion_indexversion WHERE id = NEW.index_version_id FOR SHARE;
        IF NOT EXISTS (
          SELECT 1 FROM public.workflows_runretrievalselection s
          JOIN public.releases_scenariorevision r ON r.id = s.revision_id
          JOIN public.documents_documentset d ON d.id = NEW.document_set_id
          JOIN public.documents_documentsetversion v ON v.id = NEW.document_set_version_id
          JOIN public.ingestion_indexversion i ON i.id = NEW.index_version_id
          WHERE s.id = NEW.selection_id AND s.organization_id = NEW.organization_id
            AND r.organization_id = NEW.organization_id AND d.organization_id = NEW.organization_id
            AND v.organization_id = NEW.organization_id AND i.organization_id = NEW.organization_id
            AND v.document_set_id = d.id AND i.document_set_version_id = v.id
            AND v.built_index_version_id = i.id AND v.status = 'active' AND i.status = 'active'
            AND i.store_ready AND (i.storage_layout = 'legacy' OR i.storage_state = 'sealed')
            AND EXISTS (SELECT 1 FROM jsonb_array_elements_text(r.snapshot->'data'->'document_set_ids')
                        WHERE value::bigint = d.id)
        ) THEN
          RAISE EXCEPTION 'RETRIEVAL_GENERATION_SCOPE_INVALID' USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER retrieval_generation_integrity BEFORE INSERT OR UPDATE OR DELETE
      ON public.workflows_runretrievalgeneration FOR EACH ROW
      EXECUTE FUNCTION public.agenthub_retrieval_generation_integrity();

      CREATE FUNCTION public.agenthub_retrieval_selection_complete() RETURNS trigger
      LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
      DECLARE selection_id bigint;
      BEGIN
        IF TG_TABLE_NAME = 'workflows_runretrievalselection' THEN selection_id := NEW.id;
        ELSE selection_id := NEW.selection_id; END IF;
        IF NOT EXISTS (
          SELECT 1 FROM public.workflows_runretrievalselection s
          WHERE s.id = selection_id AND s.generation_count = (
            SELECT count(*) FROM public.workflows_runretrievalgeneration g WHERE g.selection_id = s.id
          )
        ) THEN
          RAISE EXCEPTION 'RETRIEVAL_SELECTION_INCOMPLETE' USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
      END $$;
      CREATE CONSTRAINT TRIGGER retrieval_selection_complete AFTER INSERT
      ON public.workflows_runretrievalselection DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW EXECUTE FUNCTION public.agenthub_retrieval_selection_complete();
      CREATE CONSTRAINT TRIGGER retrieval_generation_complete AFTER INSERT
      ON public.workflows_runretrievalgeneration DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW EXECUTE FUNCTION public.agenthub_retrieval_selection_complete();

      CREATE FUNCTION public.agenthub_selected_generation_protected() RETURNS trigger
      LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
      BEGIN
        IF EXISTS (SELECT 1 FROM public.workflows_runretrievalgeneration WHERE index_version_id = OLD.id)
        AND (
          (NEW.organization_id, NEW.document_set_version_id, NEW.source_id,
           NEW.embedding_profile_id, NEW.dimensions, NEW.index_type)
          IS DISTINCT FROM
          (OLD.organization_id, OLD.document_set_version_id, OLD.source_id,
           OLD.embedding_profile_id, OLD.dimensions, OLD.index_type)
          OR NOT NEW.store_ready OR NEW.storage_state = 'retired'
          OR NEW.status NOT IN ('active', 'superseded')
        ) THEN
          RAISE EXCEPTION 'RETRIEVAL_GENERATION_PROTECTED' USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER selected_generation_protected BEFORE UPDATE
      ON public.ingestion_indexversion FOR EACH ROW
      EXECUTE FUNCTION public.agenthub_selected_generation_protected();
    """)


def unprotect_selection(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
      DROP TRIGGER selected_generation_protected ON public.ingestion_indexversion;
      DROP FUNCTION public.agenthub_selected_generation_protected();
      DROP TRIGGER retrieval_generation_complete ON public.workflows_runretrievalgeneration;
      DROP TRIGGER retrieval_selection_complete ON public.workflows_runretrievalselection;
      DROP FUNCTION public.agenthub_retrieval_selection_complete();
      DROP TRIGGER retrieval_generation_integrity ON public.workflows_runretrievalgeneration;
      DROP FUNCTION public.agenthub_retrieval_generation_integrity();
      DROP TRIGGER retrieval_selection_integrity ON public.workflows_runretrievalselection;
      DROP FUNCTION public.agenthub_retrieval_selection_integrity();
    """)
    for table in ("workflows_runretrievalselection", "workflows_runretrievalgeneration"):
        schema_editor.execute(f"DROP POLICY tenant_isolation ON public.{table}")
        schema_editor.execute(f"ALTER TABLE public.{table} NO FORCE ROW LEVEL SECURITY")
        schema_editor.execute(f"ALTER TABLE public.{table} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_durable_retrieval_selection"),
        ("documents", "0011_explicit_shared_data_access"),
        ("ingestion", "0020_shared_build_attempt_integrity"),
        ("releases", "0005_execution_revision_binding"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
        ("workflows", "0019_execution_revision_binding"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunRetrievalSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_key", models.CharField(max_length=200)),
                ("criteria_checksum", models.CharField(max_length=64)),
                ("generation_count", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.organization",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="releases.scenariorevision",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retrieval_selections",
                        to="workflows.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunRetrievalGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.documentset",
                    ),
                ),
                (
                    "document_set_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.documentsetversion",
                    ),
                ),
                (
                    "index_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingestion.indexversion",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.organization",
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generations",
                        to="workflows.runretrievalselection",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="runretrievalselection",
            constraint=models.UniqueConstraint(
                fields=("run", "step_key"), name="uniq_run_retrieval_step"
            ),
        ),
        migrations.AddConstraint(
            model_name="runretrievalselection",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation_count__lte", 200)),
                name="retrieval_generation_count_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="runretrievalgeneration",
            constraint=models.UniqueConstraint(
                fields=("selection", "document_set"),
                name="uniq_retrieval_generation_set",
            ),
        ),
        migrations.RunPython(protect_selection, unprotect_selection),
    ]
