# Generated by Django 5.2.16 on 2026-07-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('data_classification', models.CharField(blank=True, max_length=64)),
                ('default_locale', models.CharField(default='tr-TR', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tenancy.organization')),
            ],
            options={
                'ordering': ['organization_id', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('rag', 'RAG'), ('workflow', 'Workflow'), ('agent', 'Agent'), ('adapter', 'Adapter')], max_length=16)),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('customer_facing', 'Customer facing')], default='internal', max_length=16)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled')], default='draft', max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='catalog.aiproject')),
            ],
            options={
                'ordering': ['project_id', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.SlugField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('redirected', 'Redirected')], default='active', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_aliases', to='tenancy.organization')),
                ('redirect_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirected_aliases', to='catalog.scenario')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.scenario')),
            ],
            options={
                'ordering': ['organization_id', 'alias'],
            },
        ),
        migrations.AddConstraint(
            model_name='aiproject',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uniq_project_org_slug'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='uniq_scenario_project_slug'),
        ),
        migrations.AddConstraint(
            model_name='scenarioalias',
            constraint=models.UniqueConstraint(fields=('organization', 'alias'), name='uniq_alias_org'),
        ),
    ]
