# Generated by Django 5.2.16 on 2026-07-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_aiproject_owner_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='type',
        ),
    ]
