# Generated by Django 5.2.16 on 2026-07-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_scenario_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiproject',
            name='owner_membership',
        ),
    ]
