# Generated by Django 5.2.17 on 2026-09-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_remove_aiproject_owner_membership"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="access_revision",
            field=models.PositiveIntegerField(default=0, db_default=0),
        ),
        migrations.AddField(
            model_name="scenario",
            name="access_change_id",
            field=models.CharField(max_length=64, blank=True, default="", db_default=""),
        ),
        migrations.AddField(
            model_name="scenario",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("legacy", "Mevcut erişimi koru"),
                    ("inherit", "Projeden devral"),
                    ("private", "Bu senaryoya özel erişim"),
                ],
                db_default="legacy",
                default="legacy",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="scenario",
            constraint=models.CheckConstraint(
                condition=models.Q(("access_mode__in", ["legacy", "inherit", "private"])),
                name="scenario_access_mode_valid",
            ),
        ),
    ]
