# Generated by Django 5.2.17 on 2026-09-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_project_access_receipt"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="data_access_mode",
            field=models.CharField(
                choices=[
                    ("consumer_specific", "İstemciye özel veri"),
                    ("scenario_shared", "Senaryonun ortak verisi"),
                ],
                db_default="consumer_specific",
                default="consumer_specific",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="scenario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("data_access_mode__in", ["consumer_specific", "scenario_shared"])
                ),
                name="scenario_data_access_mode_valid",
            ),
        ),
    ]
