# Generated by Django 5.2.17 on 2026-09-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_explicit_shared_data_access"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="execution_contract",
            field=models.CharField(
                choices=[
                    ("legacy", "Mevcut sürüm çözümleme"),
                    ("scenario-revision/v1", "Tek senaryo sürümü"),
                ],
                db_default="legacy",
                default="legacy",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="scenario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("execution_contract__in", ["legacy", "scenario-revision/v1"])
                ),
                name="scenario_execution_contract_valid",
            ),
        ),
    ]
