# Generated by Django 5.2.17 on 2026-09-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_execution_revision_binding"),
        ("tenancy", "0004_remove_organizationmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="data_selection",
            field=models.CharField(
                choices=[
                    ("legacy_pinned", "Yayında seçilen veri sürümleri"),
                    ("active_generation", "Kullanıma hazır güncel veri"),
                ],
                db_default="legacy_pinned",
                default="legacy_pinned",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="scenario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("data_selection", "legacy_pinned"),
                    models.Q(
                        ("data_selection", "active_generation"),
                        ("execution_contract", "scenario-revision/v1"),
                    ),
                    _connector="OR",
                ),
                name="scenario_data_selection_valid",
            ),
        ),
    ]
