apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agenthub.fullname" . }}-config
  labels:
    {{- include "agenthub.labels" . | nindent 4 }}
data:
  {{- include "agenthub.configData" . | nindent 2 }}
