# Generated by Django 5.2.16 on 2026-07-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('input_contract', 'Input contract'), ('output_contract', 'Output contract'), ('prompt_template', 'Prompt template'), ('policy_profile', 'Policy profile'), ('model_profile', 'Model profile'), ('source_definition', 'Source definition'), ('chunking_profile', 'Chunking profile'), ('retrieval_profile', 'Retrieval profile'), ('workflow_definition', 'Workflow definition'), ('tool_definition', 'Tool definition'), ('tool_binding', 'Tool binding'), ('memory_policy', 'Memory policy'), ('eval_suite', 'Eval suite')], max_length=32)),
                ('logical_id', models.CharField(help_text="Stable identity across versions, e.g. 'customer_answer'.", max_length=128)),
                ('version', models.PositiveIntegerField()),
                ('body', models.JSONField()),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('created_by', models.CharField(max_length=200)),
                ('source_git_revision', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='tenancy.organization')),
            ],
            options={
                'ordering': ['organization_id', 'type', 'logical_id', '-version'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'type', 'logical_id', 'version'), name='uniq_artifact_org_type_logical_version')],
            },
        ),
    ]
