# Generated by Django 5.2.16 on 2026-07-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactversion',
            name='type',
            field=models.CharField(choices=[('input_contract', 'Input contract'), ('output_contract', 'Output contract'), ('prompt_template', 'Prompt template'), ('policy_profile', 'Policy profile'), ('model_profile', 'Model profile'), ('source_definition', 'Source definition'), ('chunking_profile', 'Chunking profile'), ('retrieval_profile', 'Retrieval profile'), ('workflow_definition', 'Workflow definition'), ('custom_node_definition', 'Custom node definition'), ('tool_definition', 'Tool definition'), ('tool_binding', 'Tool binding'), ('memory_policy', 'Memory policy'), ('eval_suite', 'Eval suite')], max_length=32),
        ),
    ]
